### ISSUE TITLE
WordRep install/usage

### ISSUE THREAD

**Issue by SeanDunford** [mit-nlp/MITIE#10]
Do you have any documentation on how to install or use the wordrep tool. I attempted to build it with cmake but haven't had any success. 

I attempted to adapt the steps in the ReadMe for /tools/ner_stream:

cd tools/ner_stream
mkdir build
cd build
cmake ..
cmake --build . --config Release 

but I am getting this error. 

-- Check size of void*
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JPEG_LIBRARY
    linked by target "cmTryCompileExec1671790077" in directory /mydir/mitie/tools/wordrep/build/CMakeFiles/CMakeTmp

CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Check size of void* - failed
-- Found LAPACK library
-- Found CBLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring incomplete, errors occurred!

See also "mydir/mitie/tools/wordrep/build/CMakeFiles/CMakeOutput.log".
See also "mydir/mitie/tools/wordrep/build/CMakeFiles/CMakeError.log".

**Comment by davisking** [comment]
Yeah, sorry about that.  Variations in how cmake deals with libjpeg have really been a pain lately.  Anyway, it should be fixed now.  Repull from github and it should work.

**Comment by SeanDunford** [comment]
Hey, thanks so much man. I really appreciate that.

**Comment by davisking** [comment]
No problem :)

**Comment by shubhamtalbar** [comment]
I am unable to run the command: wordrep -e /home/shubham/MITIE-wordprep
Am I missing something out?

PS: MITIE-wordprep contains all the text files of my interest

**Comment by davisking** [comment]
What happens when you run it?

**Comment by shubhamtalbar** [comment]
It says:  **wordrep: command not found**

I would be really thankful if you help me get it running.
