### ISSUE TITLE
Is it a two-step CCA to get word embedding?

### ISSUE THREAD

**Issue by wihoho** [mit-nlp/MITIE#100]
After checking the source code of `wordrep`, I found that in `get_average_context_window_vector_per_word` the word vector is directed calculated from 
` word_vectors[center_word] += join_cols(sparse_matrix_vector_multiply(trans(Ltrans), left_vect),
                                               sparse_matrix_vector_multiply(trans(Rtrans), right_vect));`.

It seems that there is no the second step CCA where
S = [LΦL RΦR]
CCA(S,W)→(ΦS,ΦW)

Can you please enlighten me on this issue? Thanks a lot.

**Comment by davisking** [comment]
That's how you do it.  You are looking at the second step right there.  This is explained in the original paper.
