### ISSUE TITLE
Entity Overlap in CoNLL NER Tasks

### ISSUE THREAD

**Issue by 2fat2kidnap** [mit-nlp/MITIE#102]
I am trying to evaluate my self-trained `total_word_feature_extractor.dat` according to the [MITIE Wiki](https://github.com/mit-nlp/MITIE/wiki/Evaluation) benchmarking guidelines.

Currently, I am trying to train MITIE on a CoNLL training dataset. However, I am running into the issue of 'overlapping entities'. For example:
`the journalist wrote` - Here, `the` gets tagged as `O` aka nothing special
`The New York Times reported` - Here, `The` gets tagged as `B-ORG`, given it is part of the NYT organisation.

There are other examples, also ones that don't have case-sensitivity involved, that have this 'double-tagging' issue. It is my understanding however that MITIE was successfully benchmarked on these corpora. How was this issue then resolved?

**Comment by davisking** [comment]
The CoNLL shared tasks we referenced don't have overlapping entities.  So I'm not sure what you are talking about.  The examples you give seem to just be labeling errors.
