### ISSUE TITLE
MITIE/dlib/dlib/image_saver/save_jpeg.cpp:89:48: error: cannot convert ‘bool’ to ‘boolean’ for argument ‘3’ to ‘void jpeg_set_quality(j_compress_ptr, int, boolean)

### ISSUE THREAD

**Issue by guojianli** [mit-nlp/MITIE#103]
MITIE/dlib/dlib/image_saver/save_jpeg.cpp:89:48: error: cannot convert ‘bool’ to ‘boolean’ for argument ‘3’ to ‘void jpeg_set_quality(j_compress_ptr, int, boolean)

compiler:
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by davisking** [comment]
Are you using the latest code in github?

**Comment by davisking** [comment]
Actually, try it now.
