### ISSUE TITLE
tokenizer() separation of punctuation and integers

### ISSUE THREAD

**Issue by 2fat2kidnap** [mit-nlp/MITIE#105]
**MITIE version:** `mitie-0.2.0`
**Python version:** `2.7.10`
**Observed behaviour:** When using the MITIE `tokenize()` function, integers seem to not be correctly separated from punctuation.
**Example to reproduce behaviour:**
```
>>> import mitie
>>> string_1 = "Germany, way back then, won the world cup."
>>> string_2 = "Germany, in 1974, won the world cup."
>>> string_3 = "Germany won the world cup in 1974."

>>> mitie.tokenize(string_1)
['Germany', ',', 'way', 'back', 'then', ',', 'won', 'the', 'world', 'cup', '.']
>>> mitie.tokenize(string_2)
['Germany', ',', 'in', '1974,', 'won', 'the', 'world', 'cup', '.']
>>> mitie.tokenize(string_3)
['Germany', 'won', 'the', 'world', 'cup', 'in', '1974.']
```
Tokenising behaviour with `string_1` is exactly as expected. However, if you look closely at `string_2`, you'll notice that it says `'1974,'` instead of `'1974', ','`. The same holds for `string_3` at the end.

Is this expected behaviour?
If this is expected behaviour, why is a distinction made between characters and integers? Is it an optimisation/efficiency choice?

**Comment by davisking** [comment]
Thanks for the bug report. 

There isn't any deep reason why it does what it does.  Although, it's too late to change since many people use MITIE and rely on it having consistent behavior, even if it might be more sensible to separate punctuation.
