### ISSUE TITLE
Is it feasible to apply online learning into MITIE?

### ISSUE THREAD

**Issue by wihoho** [mit-nlp/MITIE#109]
Hi Davis,

Again I have to disturb you, recently there is an interesting idea in my mind. Do you think it is possible to apply online learning in MITIE library to update the models periodically based on the users' operations.

I find out that there is an online learning algorithm called the pegasos algorithm in dlib. Maybe this one can be used?

**Comment by davisking** [comment]
No, that's not really going to be practical.  It's best to retrain using
the existing API.  Online learning algorithms are a lot more difficult for
the user to get right.  You would find it much less reliable than what
MITIE currently does.

**Comment by wihoho** [comment]
Thank you for your opinion. Davis
