### ISSUE TITLE
Train failed

### ISSUE THREAD

**Issue by HardikShah289** [mit-nlp/MITIE#111]
Got below exception while training...

rasa_nlu\classifiers\mitie_intent_classifier.py", line 67, in persist
self.clf.save_to_disk(classifier_file, pure_model=True)
File "mitie.py", line 732, in save_to_disk
if (_f.mitie_save_text_categorizer_pure_model(filename, self.__obj) != 0):
WindowsError: exception: access violation reading 0x00000028

**Comment by HardikShah289** [comment]
I run it as admin

**Comment by davisking** [comment]
People keep posting weird errors when using rasa nlu that only happen when using rasa nlu.  So I'm doubtful this has anything to do with MITIE.   Can you post a python script that reproduces this problem?  One that doesn't involve rasa nlu.

**Comment by HardikShah289** [comment]
I have posted on rasa nlu only but they suggest to post it here. :( 
I am not python techie, don't know how to reproduce it.

**Comment by HardikShah289** [comment]
if you can help to understand what this error is about, i can try to debug and provide some information. what is save_to_disk relation with mitie.py

**Comment by KoolCards** [comment]
I get the access violation error as well while trying to use rasa nlu.

**Comment by davisking** [comment]
rasa nlu has no affiliation with MITIE.  You should post this question on a rasa nlu forum.

**Comment by tmbo** [comment]
@davisking I would be happy to help in fixing this issue, but to be honest I am not quite sure how we could provoke an access violation by using the python mitie library. Any insights you have why the access violation might be thrown would be very helpful. 

And to be fair, there isn't something special or hacky we do when training models using mitie - thats why I'd really appreciate any input here from your side.

**Comment by davisking** [comment]
Post a minimal example program that illustrates the problem.
