### ISSUE TITLE
Import errors after compiling MITIE  using cmake.

### ISSUE THREAD

**Issue by kesak** [mit-nlp/MITIE#112]
Hi,

I  followed the instruction manual  and tried to install MITIE in Windows 10 using pip install.
It gives me error like 
    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\keerth~1\\appdata\\local\\temp\\pip-v42aoy-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\keerth~1\appdata\local\temp\pip-pcy27y-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\keerth~1\appdata\local\temp\pip-v42aoy-build\
--------------------------------------------------------------
Then I have installed MINGW and Cmake and  build the files. 

C:\mitie\MITIE-master\mitielib\build>cmake -G "MinGW Makefiles" C:/mitie/MITIE-master/mitielib/CMakeLists.txt
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/Program Files (x86)/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev2/mingw32/bin/gcc.exe
-- Check for working C compiler: C:/Program Files (x86)/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev2/mingw32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev2/mingw32/bin/g++.exe
-- Check for working CXX compiler: C:/Program Files (x86)/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev2/mingw32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring done
-- Generating done
-- Build files have been written to: C:/mitie/MITIE-master/mitielib
------------------------------------------------
when I try to run the python examples ,it says module not found.

C:\mitie\MITIE-master\examples\python>python ner.py
Traceback (most recent call last):
  File "ner.py", line 14, in <module>
    from mitie import *
  File "C:\mitie\MITIE-master\examples\python/../../mitielib\mitie.py", line 36, in <module>
    _f = ctypes.CDLL(most_recent)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

-------------------------------------------------------

Kindly help me on it.

**Comment by davisking** [comment]
The command you pasted here isn't what the instructions say to do.  They say to type this, when using cmake:

```
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```

**Comment by kesak** [comment]
Hi Davis ,

I have no experience in C++ . I just want to try MITIE libraries for NLU . but the setup is difficult as I am not sure about the softwares required to build it. kindly let me know if I have to install any additional softwares to make it work. I don't face this difficulties in linux machine. kindly help.

1) pip install is not working.
2) As you suggested in  
    https://github.com/mit-nlp/MITIE/issues/87
3) I have installed MinGW and Cmake and build the MITIE using cmake GUI and cmake -G "MinGW Makefiles" .




C:\mitie\MITIE-master\mitielib\build>cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: C:/mitie/MITIE-master/mitielib

C:\mitie\MITIE-master\mitielib\build>cmake --build . --config Release --target install
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "install"

**Comment by davisking** [comment]
Install visual studio and use that.  You will probably find that it's easier to install correctly than mingw.

**Comment by Nishabijuv** [comment]
Cmake not recognized as an internal or external command  error .
