### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by arjunmenon** [mit-nlp/MITIE#113]
That language is begging for something decent.

**Comment by marghidanu** [comment]
Maybe the Java SWIG file can be adjusted to work for Ruby or Perl

**Comment by ankane** [comment]
Hi, it's three years later, but there are now [Ruby bindings](https://github.com/ankane/mitie) for MITIE. It currently supports NER and binary relation detection with pre-trained models.

The C API was really easy to follow (thanks authors!) 🎉

**Comment by davisking** [comment]
Sweet.  I just updated the readme to note this, thanks for setting up the binding :)

**Comment by ankane** [comment]
Thanks @davisking!
