### ISSUE TITLE
Memory issue when doing entity extraction in parallel

### ISSUE THREAD

**Issue by EdwardDing** [mit-nlp/MITIE#115]
Hi, I'm trying to do multiple entity extractions in parallel in Java by feeding the same EntityExtractor. However, I keep getting  error messages indicating double free of pointer in C++

```
pointer being freed was not allocated
```

I tried to pinpoint the problem and I found that if I remove the sentence_to_feature call in `void named_entity_extractor::predict` like below, the error message is gone. 

```
// const std::vector<matrix<float,0,1> >& sent = sentence_to_feats(fe, sentence);
const std::vector<matrix<float,0,1> > sent;
```

Any ideas how to solve this problem :/?

**Comment by davisking** [comment]
You can't touch the same object from multiple threads at the same time.
