### ISSUE TITLE
Seems MITIE NER is not taking advantage of multiple threads

### ISSUE THREAD

**Issue by kiran-surya** [mit-nlp/MITIE#117]
Hi,

I'm trying to train ner on my custom data. I'm trying to set number of threads using trainer.num_threads = 32, but it seems training is not using 32 threads.

/* Console Output */
words in dictionary: 200000
num features: 271
now do training
C:           20
epsilon:     0.01
**num threads: 4**
cache size:  5
loss per missed segment:  3

/* Process Status File Output */

**Threads:        5**
SigQ:   0/241473
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000001001000
SigCgt: 0000000180000002
CapInh: 0000000000000000
CapPrm: 0000003fffffffff
CapEff: 0000003fffffffff
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
Seccomp:        0
Cpus_allowed:   ffffffff,ffffffff,ffffffff,ffffffff
Cpus_allowed_list:      0-127

Could you please let me know, what could be the issue ?

**Comment by davisking** [comment]
That's not what happens when I run it.  Post a short program that
illustrates the problem.

**Comment by kiran-surya** [comment]
Hi Davis, Thanks for the quick reply. I got the issue. I was not using the latest version of code. In the latest version this issue is fixed.
