### ISSUE TITLE
Train custom NER model in Java

### ISSUE THREAD

**Issue by Subby4Git** [mit-nlp/MITIE#12]
Hi guys,
I am using MITIE for java. I see that your example python program, shows how to train the ner, with a sentence and indices.

However, I am using MITIE for java.
How would I do the same thing in java? 

For example, I need to train the NER, to extract the 'holiday' entity from: When is Christmas?
I am using the compiled java library you linked to.

Is the NER process fast, and does it consume a lot of memory?

P.S. By the way, for NER, is this library better than OpenNLP and others? What's the advantage in using this library over others? Does it have state of the art advanced algorithms?

**Comment by davisking** [comment]
You train the model using python or C++ and then load the model file in java.  Right now there isn't a training API for java.

Yes, MITIE is state-of-the-art (http://blog.dlib.net/2014/04/mitie-completely-free-and-state-of-art.html) and very fast.  The NER in OpenNLP is not very good.  There is a Stanford library that is just as accurate as MITIE but it's not free for commercial use.  

Also, running MITIE consumes basically just the amount of memory for loading the model file.

**Comment by Subby4Git** [comment]
This is like my dream come true! 
Also, will you guys add a training api for java? 



—

**Comment by davisking** [comment]
Sweet :)

It's on our list, but it's somewhat lower priority than other things since
most people are fine running the training in python and then using the
model via whatever API they like.

**Comment by d-kum** [comment]
hi. i am new to python and trying out MITIE Python API to train a named_entity_extractor. But i am getting Undefined variable: ner_training_instance error. How can i resolve that?

**Comment by davisking** [comment]
Try running the example programs in the examples folder.  Those will definitely work.

**Comment by davisking** [comment]
There is now a MITIE Java API thanks to this PR https://github.com/mit-nlp/MITIE/pull/32
