### ISSUE TITLE
Install target for Java Interface

### ISSUE THREAD

**Issue by mcelvg** [mit-nlp/MITIE#120]
Adding:

`MESSAGE( STATUS "CMAKE_PARENT_LIST_FILE: " ${CMAKE_PARENT_LIST_FILE} )`

immediately before [cmake_swig_jni#L185](https://github.com/mit-nlp/MITIE/blob/master/mitielib/java/cmake_swig_jni#L185) shows `CMAKE_PARENT_LIST_FILE` pointing to `/path/to/MITIE/mitielib/java/cmake_swig_jni` (instead of the path to "CMakeLists.txt".)

Changing [cmake_swig_jni#L185](https://github.com/mit-nlp/MITIE/blob/master/mitielib/java/cmake_swig_jni#L185) to:

`string(REGEX REPLACE "cmake_swig_jni$" "" base_path ${CMAKE_PARENT_LIST_FILE})`

puts "libjavamitie.jnilib" and "javamitie.jar" in the correct folder (`MITIE/mitielib/`).

Not sure why `CMAKE_PARENT_LIST_FILE` is pointing to "cmake_swig_jni", seems like it should be "CMakeLists.txt" from the documentation: https://cmake.org/cmake/help/v3.7/variable/CMAKE_PARENT_LIST_FILE.html

====
cmake version 3.7.1
swig 3.0.6
jdk 1.8.0.45
clang 8.1.0.8020042
macOS 10.12.4

**Comment by davisking** [comment]
Huh, yeah, that's not how cmake used to behave.  Thanks for pointing this out. I just pushed a fix to github so it should work properly now on both old and new versions of cmake.
