### ISSUE TITLE
Hyperparameters in MITIE?

### ISSUE THREAD

**Issue by nsanthanam** [mit-nlp/MITIE#121]
Are there any hyperparameters in MITIE that we can play with while building NER models? The [Python example](https://github.com/mit-nlp/MITIE/blob/master/examples/python/train_ner.py) in the `examples` I looked at didn't have any tuning, so it'd be great to see an example of how it's done.

Thanks!

**Comment by davisking** [comment]
No.  MITIE does all that stuff internally so you don't have to.  That's basically the main design principle of MITIE.
