### ISSUE TITLE
Structure encoding in MITIE

### ISSUE THREAD

**Issue by nsanthanam** [mit-nlp/MITIE#122]
I'm building an NER model for location using the [CoNLL 2003 ](http://www.cnts.ua.ac.be/conll2003/ner/) dataset for training. I've noticed something strange when I'm evaluating the model. If I give it a sentence like `can i pick it up from chicago`, MITIE identifies `chicago` as the location and `score=0.24595138696422633`. However, if I just change one character and the input sentence is `can i pick it up from chicaga` (`chicago` is changed to `chicaga`), the model fails to detect `chicaga` as the location. Given that it should (?) be learning the structure of the sentence, I would have expected it to get both locations.

Given that this is the case, is MITIE doing character-level embedding? This was my first suspicion when I saw this, but I'd like to verify that it is the case.

If not, would you happen to know why it's happening? And how I could possibly get the model to generalise to new locations given the same (or similar) structure?

Thanks!

**Comment by davisking** [comment]
It takes a lot of data to learn.  Maybe you just didn't give it enough.  I have a feeling you are training it on just one sentence?

In addition, the total word feature extractor model that comes with MITIE knows a whole lot about English, both about many specific words as well as a lot about word morphology.  So it's almost certainly going to know that chicago is something special even before you give it any labeled NER data.

**Comment by anujgupta82** [comment]
@davisking : We are not training on just one sentence but as @nsanthanam said "whole of CaNLL dataset."

How does MITIE's word feature extractor model handle a unknown word ?
i.e. in the Training set it has seen Chicago but not Chicaga. So, Chicaga is a word it has never seen. In such a case how is it handled ?

**Comment by davisking** [comment]
It includes a lot of word morphology in the construction of the word vector.  So it still does something useful.

**Comment by grafael** [comment]
@davisking it's possible to extend the word vector generated by the tool "wordrep" ? I mean, there popular implementations like word2vec and GloVe, it's possible to take advantages of that ? or the word vector used in MITIE stands for something different?

**Comment by davisking** [comment]
Many things are possible.  I doubt what you are suggesting will make it better though.  I selected the eigenvectors MITIE uses because they were better than word2vec in multiple experiments.
