### ISSUE TITLE
Suggestion for how to define the NER entity or relation extractor.

### ISSUE THREAD

**Issue by s9amaska** [mit-nlp/MITIE#129]
Hi, the tool is really awesome, thanks!

I'm trying to extract some specific information from our texts, which are event descriptions, using training a new NER model and Relation extractor. What I'm not sure about is how exactly to define our entity to get the best result. Let me give an example of a text and our desired output:
input: "Party! Party! Tonight there is Party in our Club and the entrance fee is for free! but only till 11pm. Afterwards it's 6$. Bring your friends and have fun."
desired output: "Entrance fee is for free! but only till 11pm. Afterwards it's 6$."
Is it fine to define the whole chunk as an entity and make thousands of examples for training the model? (A long sentence as an entity)
Or is it better to define "entrance", "for free", "till 11pm" and "afterwards 6$" as entities and define some sort of relations between them using the Relation Extractor Trainer in order to extract the info.?

Thank you in advance

**Comment by davisking** [comment]
In general, you want to define things in a consistent way.  It doesn't necessarily matter how long the entities are.  However, the only way to know what is best is to try it and see what happens.

**Comment by s9amaska** [comment]
@davisking Thank you very much for answering.
I have tried both ways. The model finds the important information correctly but it also detects other parts of text as entities mistakenly. Does it make sense to have some training sentences without any entity in them, to have negative instances?

**Comment by davisking** [comment]
Having sentences without any entities is fine.   More generally, add more training data and you will probably get better results.
