### ISSUE TITLE
Cannot install mitie on python 3 with pip install git+https://github.com/mit-nlp/MITIE.git

### ISSUE THREAD

**Issue by KoolCards** [mit-nlp/MITIE#131]
![image](https://cloud.githubusercontent.com/assets/13671575/26617425/fd67da76-4589-11e7-9f12-b7f504c72f08.png)

Error does not allow for installation of mitie on windows with python 3 and pip.

**Comment by davisking** [comment]
Yeah, that doesn't work on windows.  Just use cmake instead as the instructions on the front page of MITIE show.

**Comment by prasu1222** [comment]
i got the same error but i did not understand you answer can you explain this for me

**Comment by davisking** [comment]
Run this 
```
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```
Then go into the example program and try to run the python examples.

**Comment by prasu1222** [comment]
i tried to execute this command

pip3 install git+https://github.com/mit-nlp/MITIE.git

Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\kumarp5d\appdata\local\temp\1\pip-req-build-ce9wxmzc
Building wheels for collected packages: mitie
  Building wheel for mitie (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\kumarp5d\desktop\learning\chatbot project\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KUMARP5D\\AppData\\Local\\Temp\\1\\pip-req-build-ce9wxmzc\\setup.py'"'"'; __file__='"'"'C:\\Users\\KUMARP5D\\AppData\\Local\\Temp\\1\\pip-req-build-ce9wxmzc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-wheel-q0i4n3j3'
       cwd: C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-req-build-ce9wxmzc\
  Complete output (53 lines):
  running bdist_wheel
  running build
  -- Building for: NMake Makefiles
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as

      project(ProjectName)

    near the top of the file, but after cmake_minimum_required().

    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error in CMakeLists.txt:
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/KUMARP5D/AppData/Local/Temp/1/pip-req-build-ce9wxmzc/mitielib/build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-req-build-ce9wxmzc\setup.py", line 67, in <module>
      'License :: Boost License',
    File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\kumarp5d\desktop\learning\chatbot project\venv\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-req-build-ce9wxmzc\setup.py", line 23, in run
      subprocess.check_call(['cmake', '..', '-A', 'x64'])
    File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '..', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for mitie
  Running setup.py clean for mitie
Failed to build mitie
Installing collected packages: mitie
    Running setup.py install for mitie ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kumarp5d\desktop\learning\chatbot project\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KUMARP5D\\AppData\\Local\\Temp\\1\\pip-req-build-ce9wxmzc\\setup.py'"'"'; __file__='"'"'C:\\Users\\KUMARP5D\\AppData\\Local\\Temp\\1\\pip-req-build-ce9wxmzc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-record-h5umnizo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kumarp5d\desktop\learning\chatbot project\venv\include\site\python3.6\mitie'
         cwd: C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-req-build-ce9wxmzc\
    Complete output (54 lines):
    running install
    running build
    CMake Warning (dev) in CMakeLists.txt:
      No project() command is present.  The top-level CMakeLists.txt file must
      contain a literal, direct call to the project() command.  Add a line of
      code such as

        project(ProjectName)

      near the top of the file, but after cmake_minimum_required().

      CMake is pretending there is a "project(Project)" command on the first
      line.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    CMake Error in CMakeLists.txt:
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.


    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/KUMARP5D/AppData/Local/Temp/1/pip-req-build-ce9wxmzc/mitielib/build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-req-build-ce9wxmzc\setup.py", line 67, in <module>
        'License :: Boost License',
      File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\kumarp5d\desktop\learning\chatbot project\venv\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-req-build-ce9wxmzc\setup.py", line 23, in run
        subprocess.check_call(['cmake', '..', '-A', 'x64'])
      File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '..', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kumarp5d\desktop\learning\chatbot project\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KUMARP5D\\AppData\\Local\\Temp\\1\\pip-req-build-ce9wxmzc\\setup.py'"'"'; __file__='"'"'C:\\Users\\KUMARP5D\\AppData\\Local\\Temp\\1\\pip-req-build-ce9wxmzc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KUMARP5D\AppData\Local\Temp\1\pip-record-h5umnizo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kumarp5d\desktop\learning\chatbot project\venv\include\site\python3.6\mitie' Check the logs for full command output.



So now i have downlaod the git repository and placed in sit packages and run  the suggested commands but it throws the error  

here is the error while running the last line

C:\Users\KUMARP5D\Desktop\Learning\Chatbot Project\venv\Lib\site-packages\MITIE-master\mitielib\build>cmake --build . --config Release --target install
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: nmake /nologo install &&

**Comment by davisking** [comment]
You have to install an appropriate compiler.  Since you are on windows you should install visual C++.
