### ISSUE TITLE
[Ask] what does these numbers mean

### ISSUE THREAD

**Issue by egregorius** [mit-nlp/MITIE#132]
Hi,

I just want to ask, for word vects, why did you choose these numbers?

    vocab_size = 200000;
    window_size = 9;
    num_contexts = 50000000;
    num_correlations = 90;

Thank you.

**Comment by davisking** [comment]
Because they give good results.   You can try changing them to see what happens though.  They aren't the only possibly settings that will give good results.

**Comment by davisking** [comment]
I should also point out that the functions being called there are in dlib and those functions are all fully documented.  The main one being dlib::cca().
