### ISSUE TITLE
Tokenizer ignoring period 

### ISSUE THREAD

**Issue by vinvinod** [mit-nlp/MITIE#133]
This happens when the period is after a two letter word with first letter in caps.
Let me explain the issue with an example.

```python
>>> from mitie import tokenize
>>> text = "My name is Ab. Vinod."
>>> print(tokenize(text))
['My', 'name', 'is', 'Ab', 'Vinod', '.']
```
`.` after `Ab` is not in the tokens list

Other cases which are working
```python
from mitie import tokenize
text = "My name is AB. Vinod."
print(tokenize(text))
['My', 'name', 'is', 'AB', '.', 'Vinod', '.']

text = "My name is ab. Vinod."
print(tokenize(text))
['My', 'name', 'is', 'ab', '.', 'Vinod', '.']
```

**Comment by davisking** [comment]
That's not a bug, it's done one purpose.  If you want to tokenize things differently you should use a different tokenizer.

**Comment by vinvinod** [comment]
Ok thanks
