### ISSUE TITLE
The MITIE training takes so long time

### ISSUE THREAD

**Issue by xliuhw** [mit-nlp/MITIE#134]
I am using the MITIE text categorizer as the intent training and using MITIE NER for the entity training.
I tried 60 classes/intents with 11K training samples and 140 labels/entities with 23K training samples. Both took over 70 hours so total around 150 hours.

I suspect something wrong with my data labelling. My first concern is about entity label consistence issue. Some same entities are across different intent classes but annotated differently (differently even within the same intent class). e.g.

tell me the [news_type : world] news
tell me the [news_type : international] news
tell me the [news_type : sports] news
tell me the news in [location : London]
tell me the news in [location : New York]
tell me the news in the [location : world]

The "world" is labelled as news_type in the first sentence sample but labelled "location" in the
last sentence sample.

other similar ones like [location : London] in some intents but [city_name : London] in other intents.

What I am not so sure is: will this kind of entity annotation (same word/phrase with different label names in differnt scenarios) affect much about the training speed and accuracy?

Another question: I notice some entities have around 200 samples but some only have 10 or 20 samples, will this be an issue? Should I certainly need to make sure the number of the samples are balanced across the entities?

Your suggestions/advices will be greatly appreciated!

**Comment by davisking** [comment]
That's a long time.  It's likely due to your data being difficult to separate.  But it kinda is what it is.  Part of the reason MITIE takes a longish time to train is because it does a lot of internal validation so that you don't have to mess with anything.  You could instead use the machine learning tools in dlib directly if you wanted more control.
