### ISSUE TITLE
How to create a new .dat (Dataset) for Portuguese?

### ISSUE THREAD

**Issue by vinistig** [mit-nlp/MITIE#135]
Hi Guys,

I need to know what is the .dat file used in models, and what a need to pass to 'wordrep' to create my dataset? I have created a .dat file using that tool but i don't know what is stored on that. Have any software to open this data file specifically?

What is the specifically text format i need to pass the 'wordrep' to generate the .dat file?

**Comment by oximer** [comment]
I also having the same doubt! This training part is really clear to me.

What are the inputs for wordrep?
How to generate a pure ner for my language?

**Comment by davisking** [comment]
wordrep just takes a folder with a bunch of .txt files as input.  It doesn't matter what the format is so long as it's the same format use you use when you use MITIE in your application.  In general, I encourage people to use utf-8.  

As for what is 'in' the .dat file.  It's a whole bunch of data useful for modeling word morphology and notional relationships.  You don't need to know what's in the file to use MITIE.  But if you want a background in how MITIE works you should look at the sequence labeling tooling in dlib and the two step cca paper (https://arxiv.org/abs/1206.6403) as starting points.
