### ISSUE TITLE
Adding 30M entities

### ISSUE THREAD

**Issue by zakmandhro** [mit-nlp/MITIE#136]
Hi all, I am working on a project that requires NER for 30M entities with 3 intents. Is this something MITIE is well suited for? If so, is there a better way to train MITIE for the named entities part other than using `/python/train_ner.py`?

**Comment by davisking** [comment]
Do you mean 30 million separate label categories?

**Comment by zakmandhro** [comment]
Hi Davis, 3 label categories (e.g. "Movie", "TV show", "music video"), 30 million distinct entities (e.g. "Star Wars", "Game of Thrones", "Hello - Adele".

**Comment by davisking** [comment]
Then MITIE should work fine for this task.

**Comment by grafael** [comment]
By the way, what if I train 100, 1000 of distinct entities? I mean not only ORG, PERSON ... but thousands of entities? Will the algorithm fit well? In other words, the large number of instances seems to work well during the training phase, but the number of entities has some limitation?  What else could increase the time of training phase?

**Comment by davisking** [comment]
That's fine.  It will just require more RAM.
