### ISSUE TITLE
feature for segmenter and classifer

### ISSUE THREAD

**Issue by kwkwvenusgod** [mit-nlp/MITIE#137]
MITIE provides a good pipeline for NER training and recognition, first it is segmenter training for sequential labeling problem, the second step is the classifier training to classify the recognition of named-enity. Can I know the difference of the feature applied to different training procedure. From what I observed, the segmenter training only uses pretrained word embedding and the latter part both use word embedding and other kind of features, like is capital etc. First I want to know whether my observation is correct or not? If I am correct, why don't you apply s_all_numbers, contains_hyphen, is_caps such kind of feature on segmenter training in the first step? Thank you very much

**Comment by davisking** [comment]
Yes, that's how it works.  

It's that way because adding those features to the segmentation didn't improve the accuracy on standard benchmarks.
