### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by oximer** [mit-nlp/MITIE#139]
Do we have a Gitter community? 

I have trained MITIE for Portuguese, but I want to discuss more about it with other developers that have it do for other languages.

I'm pretty sure that I have done something wrong.

**Comment by davisking** [comment]
I haven't setup anything like that.  Personally, I'm not going to hang out in a chat room.

**Comment by oximer** [comment]
I see.

So let me explain my scenario, so maybe you could help me here.

I downloaded wiki dump and used it on Wordrep to obtain an total_word_feature_extractor.
After it, I trained the ner_model.dat using this repo java example.
At this, point seems to me that I have a trained and ready MITIE.

However, I'm troubled by the fact that training MITIE seems really simple.
As an example, [Spacy](https://spacy.io/docs/usage/adding-languages) seems much more complicated. I have to deal with Stop words, Tag maps, Tokenizer exceptions...

Why MITIE doesn't requires it? I'm missing anything?
Why so huge difference?

**Comment by davisking** [comment]
The point of MITIE is to be easy to use.  So it's easy to use.

**Comment by oximer** [comment]
I imagine that it might have some performance cost.
I'm wrong about?

**Comment by davisking** [comment]
Being difficult to use doesn't mean it's better.
