### ISSUE TITLE
[Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by vijaypatil123** [mit-nlp/MITIE#140]
Hi 
I am executing below command for RASA-nlu, But getting exception.

Operating System : Windows 7

Command: pip install git+https://github.com/mit-nlp/MITIE.git

Exception:
_Installing collected packages: mitie
  Running setup.py install for mitie ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\.......\\appdata\\local\\temp\\pip-xuhigl-build
\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\
r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:
\users\........\appdata\local\temp\pip-rwhjre-record\install-record.txt --single
-version-externally-managed --compile:
    running install
    running build
    error: [Error 2] The system cannot find the file specified

Tried to install MITIE.git directly, but still getting same error.

**Comment by davisking** [comment]
Use the cmake instructions when installing windows.
