### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by grafael** [mit-nlp/MITIE#142]
I have two datasets the first one has 1000 sentences and the second just 600. Both are trained to classify 150 entities. When I train the first dataset (1000 sentences) after a couple of hours I get the model trained, but in the second dataset (600) seems taking forever.

**My question is:**  What in the dataset could be influencing the training time? The number of tags per sentence? 
_I'm asking that because I was expecting that 600 sentences should train faster than 1000._

**Comment by davisking** [comment]
That could happen.  The running time is also dependent on how separable your data is.  If there are a lot of things in your dataset that aren't labeled consistently or are impossible to distinguish between each other or very difficult then training will take longer.
