### ISSUE TITLE
Training a custom NER model

### ISSUE THREAD

**Issue by sandeeppilania** [mit-nlp/MITIE#143]
I need a clarification on training dataset for custom NER model.
Like do we have to use the same formats as in the examples given in train_ner
sample = ner_training_instance(["My", "name", "is", "Davis", "King", "and", "I", "work", "for", "MIT", "."])
sample.add_entity(xrange(3,5), "person")
or is there any other format which can be used.
As this could be a tedious task to do for 10K sentences.

**Comment by davisking** [comment]
Not sure what you mean by 'formats'.  You call the functions shown with those kinds of inputs.

**Comment by sandeeppilania** [comment]
ya, i meant that only. So, we have to call these function with the same kind of inputs for each sentence. Right?

**Comment by sandeeppilania** [comment]
And one more query i have, is there any way to combine two classification models, like the pretrained ner model with custom NER model?

**Comment by davisking** [comment]
Yes, the examples show you how to use the API.

No, you can't combine models.
