### ISSUE TITLE
Actual trained intent name not returned and slow classification

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mit-nlp/MITIE#145]
Hi guys, using the following:

```
#!/usr/bin/python

import sys, os
parent = os.path.dirname(os.path.realpath(__file__))
sys.path.append(parent + '/../../mitielib')

from mitie import *

sample = ner_training_instance(["Tell", "me", "more", "about", "the", "Artificial", "Intelligence", "E-Commerce", "Store","."])
sample.add_entity(xrange(5,9), "Product")

sample2 = ner_training_instance(["I", "am", "interested", "in", "the", "Artificial", "Intelligence", "E-Commerce", "Store","."])
sample2.add_entity(xrange(5,9), "Product")

sample3 = ner_training_instance(["Can", "you", "take", "me", "to", "the", "login", "page","?"])
sample3.add_entity(xrange(6,7), "Product")

trainer = ner_trainer("../../MITIE-models/english/total_word_feature_extractor.dat")

trainer.add(sample)
trainer.add(sample2)
trainer.add(sample3)

trainer.num_threads = 4

ner = trainer.train()

ner.save_to_disk("new_ner_model.dat")

print ("tags:", ner.get_possible_ner_tags())

tokens = ['hello', 'there', 'I', 'am', 'interested', 'in', 'the', 'Artificial', 'Intelligence', 'E-Commerce', 'Store','.']
entities = ner.extract_entities(tokens)

print ("\nEntities found:", entities)
print ("\nNumber of entities detected:", len(entities))
for e in entities:
    range = e[0]
    tag = e[1]
    entity_text = " ".join(tokens[i] for i in range)
    print ("    " + tag + ": " + entity_text)
```
I get the output:

```
('tags:', ['Product'])
('\nEntities found:', [(xrange(7, 11), 'Product', 0.0)])
('\nNumber of entities detected:', 1)
    Product: Artificial Intelligence E-Commerce Store
```
Added into  pipeline before my custom intent classifier I have the following:

```
tokens = nltk.word_tokenize(sentence)				
ner = named_entity_extractor('new_ner_model.dat')
entities = ner.extract_entities(tokens)
for e in entities:
	range = e[0]
	tag = e[1]
	score = e[2]
	score_text = "{:0.3f}".format(score)
	entity_text = " ".join(tokens[i].decode() for i in range)
	print("   Score: " + score_text + ": " + tag + ": " + entity_text)
```
With the sentence:

`Hi I am interested in the artificial intelligence e-commerce store`

It gives me:
   
`Score: 0.000: Product: artificial intelligence e-commerce store`

Strangely (I think) if I used the following sentence:

`Hi I am interested in the artificial intelligence e-commerce system`

It gives me:

`Score: 0.000: Product: artificial intelligence e-commerce system`

Even though artificial intelligence e-commerce system has not been trained as an entity, is this expected behaviour and how do I increase the confidence seeing as it has not be trained anything else it should have a high confidence no?

Also it takes up to ten seconds to detect sometimes more to detect entities which drastically slows down my program, any advice on speeding this up I am worried that once there are a lot of entities it is going to take forever to get results.

Thanks in advance

**Comment by grafael** [comment]
Try add one more entity... not just Product

**Comment by AdamMiltonBarker** [comment]
Thanks for the reply, I noticed I had not added the right intent name for the login page, changing this made it work correctly. Any idea on speeding up the process, it is very slow to detect an entity.

**Comment by AdamMiltonBarker** [comment]
The way that it does not return the actual entity name is also an issue, is this able to be resolved ? 

With the labelled entity Artificial Intelligence E-Commerce Store:

>> I am interested in the artificial intelligence e-commerce store

```
{'Received': 'I am interested in the artificial intelligence e-commerce store', 'Confidence': 0.99691617, 'Intent': u'InterestedIn', 'Responses': [u'No problem, I will take you to the Artificial Intelligence E-Commerce page', u'One moment, I will take you to the Artificial Intelligence E-Commerce page'], 'Entities': [{'Score': '0.231', 'Entity': u'artificial intelligence e-commerce store'}], 'Action': u'GoToProduct', 'ContextIn': 'NA', 'ContextCurrent': u'', 'Response': u'No problem, I will take you to the Artificial Intelligence E-Commerce page', 'ContextOut': u''}
```

>> I am interested in the artificial intelligence e-commerce

```
{'Received': 'I am interested in the artificial intelligence e-commerce', 'Confidence': 0.99021143, 'Intent': u'InterestedIn', 'Responses': [u'No problem, I will take you to the Artificial Intelligence E-Commerce page', u'One moment, I will take you to the Artificial Intelligence E-Commerce page'], 'Entities': [{'Score': '0.161', 'Entity': u'artificial intelligence e-commerce'}], 'Action': u'GoToProduct', 'ContextIn': 'NA', 'ContextCurrent': u'', 'Response': u'No problem, I will take you to the Artificial Intelligence E-Commerce page', 'ContextOut': u''}

```

It does not return the correct entity name, the last example above returns "artificial intelligence e-commerce", it should return  "Artificial Intelligence E-Commerce Store" case sensitive and correct entity name, this is a game breaker in my program, hoping there is a way around it.

**Comment by AdamMiltonBarker** [comment]
I think if I edit this:

https://github.com/mit-nlp/MITIE/blob/c8da90493ea258503d004bbb24bf0b2b09df02bc/mitielib/mitie.py#L287

I can make it return the actual entity name it was trained, I cannot locate this file on my system though, any ideas where it may be ?

**Comment by davisking** [comment]
No, that's not a reasonable thing to do.  You can do exactly what you want without modifying MITIE.  You aren't getting answers to your questions here because you are asking basic python programming questions, rather than questions specific to MITIE.  You should find a good python tutorial, course, or internet forum about learning python generally if you want help learning to program in python.

**Comment by AdamMiltonBarker** [comment]
This is a question related to MItie not Python, FYI I was a teaching assistant for MIT's Computer Science course with Python, so I do not believe I need a course on Python. The questions remaining are:

Is there a way to speed up the process of MITIE
Why does Mitie not return the actual named entity

**Comment by AdamMiltonBarker** [comment]
@davisking to be honest mate, you are pretty damn rude,  having checked how you reply to others it seems it is your character. Will move to a different entity extractor.

**Comment by davisking** [comment]
Your code shows that you are reloading the model file on every call.  That's not a mistake someone conversant in programming should make.  Don't do that and it will run much faster.

MITIE doesn't output any entity text at all.  Look at your code you posted.  The text is text you input to MITIE in the first place.  The only output of entity extraction is a class label (that the user defines as whatever they want), and a numeric range that tells you what tokens the ID applies to.  The "not the right text" you posted is **_text you made with your code_**, not from MITIE.

**Comment by AdamMiltonBarker** [comment]
@davisking  The model loading takes less than a second, it is the actual detection that takes the time, also there are multiple models, the model needs to be loaded based on the current model the program is querying, the model loader is not in a loop, so you actually guessed that I loaded the model each time. 

You are correct with your last answer that is exactly the thing I am asking about why does it not return the actual named entity it was trained with, in the examples, you just use the tokens and the range and that is provided in the print, not actually returned from Mitie, which is my whole reason of asking the question, I need to access the ACTUAL named entity that was trained to it, not a variation of that.

**Comment by AdamMiltonBarker** [comment]
@davisking please see above.

**Comment by AdamMiltonBarker** [comment]
@davisking The model loading takes less than a second, it is the actual detection that takes the time, you can see this quite easily just using your training example. In my program each user has their own model so yes each time they access the program it will load their own model, this is an API application for a bot with multiple users and multiple models. The training code above is your own training code and in another file all I have added is your ner.py example with exception to the tokenizer which is NLTK.

In my program directly after the entity extraction it loads my custom intent classifier and classifies the intent within seconds on a very large model, adding in Mitie has reduced a second response time to above 10. 

You are correct with your last answer that is exactly the thing I am asking about, why does it not return the actual named entity it was trained with, in the examples, you just use the tokens and the range and that is provided in the print, not actually returned from Mitie, which is my whole reason of asking the question, I need to access the ACTUAL named entity that was trained to it, not a variation of that. There is not a way that I can think of to match the actual entity when this is running in another program from the training, I only hardcoded the string for example, it is not a hard coded string in the application.

IE:

"Artificial", "Intelligence", "E-Commerce", "Store" is the actual named entity trained, yet, "artificial", "intelligence","e-commerce" is recognized, that is great, if it returns the actual named entity of Artificial Intelligence E-Commerce Store, which it is not doing.

To save any more hassle as it is pretty clear you would rather jump the gun as to what you think my issue is after clearly not understanding the issue, could you tell me where the library files are located as searching for mitielib or mitie returns nothing but the models folder.

**Comment by davisking** [comment]
I think there is confusion about what MITIE does.  Getting "the actual named entity it was trained with" isn't a thing.  Each type of named entity is generally trained with hundreds or thousands of separate examples of that entity type.  There is no such thing as "the one string for that entity during training".  It could be any number of a huge variety of strings.

**Comment by AdamMiltonBarker** [comment]
Maybe if I give you what I am trying to achieve and you could point me in the direction or say it is not possible, I believe I have a way to fix to work how I need it but I cannot locate mitielib anywhere on my Linux box.

I am writing my own solution to API.ai, I have everything complete with exception to a few things, one being entity extraction. 

In API.ai, do you have Entities, IE Products is an entity then you have references and synonyms related to those references, when you query API.ai, it returns the entity type Product, and reference, Artificial Intelligence E-Commerce Store, if it matched that entity with Artificial Intelligence E-Commerce, it would still return the trained reference of Artificial Intelligence E-Commerce Store, not Artificial Intelligence E-Commerce, this is what I need to achieve.

**Comment by AdamMiltonBarker** [comment]
@davisking I have solved this by mapping synonyms to entities, I still feel this is overkill, I will play around with the source when I get some time so it can include synonyms and correct values.
