### ISSUE TITLE
Mitie (not Python related) issues.

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mit-nlp/MITIE#146]
Sorry but you closed an issue stating is was Python related which it is not it is related to Mitie.

Is there a way to speed up the process of Mitie
Why does Mitie not return the actual named entity. Mitie does not return the actual named entity, feel free to tell me how that is related to Python and not Mitie.

**Comment by davisking** [comment]
Don't duplicate issues.

**Comment by AdamMiltonBarker** [comment]
I wouldnt of needed to if the questions regarding Mitie had been answered instead of fobbed off.
