### ISSUE TITLE
MITIE  memory requirements for best results.

### ISSUE THREAD

**Issue by SreejeshPM** [mit-nlp/MITIE#147]
Hi team,

We are using MITIE for Entity recognition in one of our project. The MITIE is working fine when mapped against less number of entities. But when it mapped against 15  entities (approx). The celery job (our Job scheduler) is taking huge amount of time and memory to complete around (10-11 hours). 

Could you please let us know the best configuration for MITIE to work on seamlessly. Specification like RAM and OS will be great. 

Thanks in advance.
Sreejesh

**Comment by davisking** [comment]
OS doesn't matter.  Also, so long as you have enough RAM that the OS isn't swapping pages to disk you are fine.  

Some datasets take a long time for the solver to process.
