### ISSUE TITLE
Mitie installation failing on Windows 10

### ISSUE THREAD

**Issue by ankitarath2011** [mit-nlp/MITIE#149]
I tried executing "cmake --build . --config Release --target install". But getting following error.

The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "install"

Can you please help me.

**Comment by davisking** [comment]
Post the entire output

**Comment by ankitarath2011** [comment]
I am getting this much output only. 

The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "install"

I have VC++ 10 installed.

**Comment by ankitarath2011** [comment]
Actuallu for "cmake .. " command also I am getting some error I think. Please find below the output of cmake ..

```
C:\Users\ankita.a.rath\Downloads\MITIE-master\mitielib\build>cmake ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error in CMakeLists.txt:
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/ankita.a.rath/Downloads/MITIE-master/mitielib/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/ankita.a.rath/Downloads/MITIE-master/mitielib/build/CMakeFiles/CMakeError.log".
```

**Comment by davisking** [comment]
That error is telling you that you don't have a C++ compiler.  You have to install visual studio to compile the code.

**Comment by ankitarath2011** [comment]
Thanks. Issue resolved. 
But got into some other problem. When I am running the examples it is executing fine, but when I am trying to import mitie in some other file it is saying no module named mitie

**Comment by davisking** [comment]
You have to add the mitie shared library into your python path.  Look at the example programs, they contain the code that does this.  Or google it, there are a lot of ways to add things to your pyhton path.

**Comment by kunalm37** [comment]
I am also facing the same issue. I am not able to link MITIE with Python on windows machine.

**Comment by suvarnaR** [comment]
I am facing the same issue but linking MITIE with golang on windows 7 machine

**Comment by kunalm37** [comment]
I found out a way for installing MITIE NLP in Windows, here is the steps I followed: [Steps for installing MITIE NLP in Windows](https://stackoverflow.com/questions/47567251/how-to-install-mitie-nlp-on-windows-for-rasa-nlu)

**Comment by suvarnaR** [comment]
thanks for your reply but this is with python i am trying for golang

**Comment by kunalm37** [comment]
First clone the entire [MITIE repository](https://github.com/mit-nlp/MITIE)
First step in WindowsDownload Visual Studio 2015 Build Tools for C++from this [link](http://landinghub.visualstudio.com/visual-cpp-build-tools)

Build all the directories in the `~\MITIE-master\tools` first using developer command prompt VS2015:
i) `mkdir build`
ii) `cd /D build`
iii) `cmake -G "Visual Studio 14 2015 Win64" ..`
iv) `cmake --build . --config Release --target install` 

Now use the appropriate exe which is located under `train_ner > Build > Release > train_ner_example.exe ` folder to invoke it via Golang.
