### ISSUE TITLE
Amazon always (or at least incredibly often) tagged as a location and McDonald's as a person

### ISSUE THREAD

**Issue by AWNystrom** [mit-nlp/MITIE#15]
Hello,

First I'd like to thank the makers of MITIE. It's great to have a state-of-the-art NER free for commercial use. I've been finding that it has issues identifying Amazon and McDonald's as companies, as described below.

Throughout this post I'll run the following code with different input and display the output:

toks = mitie.tokenize(eatiht.extract(fd))
ents = ner.extract_entities(toks)
[(e[1], ' '.join(toks[e[0][0]:e[0][-1]+1]), e[2]) for e in ents]

I've been finding that Amazon is usually tagged as a location. Here's an example of such a text:

"Amazon is among a host of companies asking the Federal Aviation Administration to expand the abilities of small commercial drones and the traffic control system that would monitor them."

which yields

[('LOCATION', 'Amazon', 0.6497587837582173),
 ('ORGANIZATION', 'Federal Aviation Administration', 1.2338242977625724)]

Here's another:

'Its earnings season again and Amazon, for the first time ever, has broken out the financial results of its cloud services division, Amazon Web Services (AWS).  The results  are impressive.  In less than a decade, Amazon has grown AWS into a $5 billion business that is still growing at 50%.'

which yields

[('LOCATION', 'Amazon', 0.6857005959408439),
 ('ORGANIZATION', 'Amazon Web Services', 0.8302322174217054),
 ('LOCATION', 'Amazon', 0.5971181888647527)]

I've been finding similar problems with McDonald's. Take this story, for example: http://www.foxnews.com/leisure/2015/04/27/not-lovin-it-mcdonald-is-trying-to-fix-its-business/

which yields

[('PERSON', 'McDonald', 0.5934354493699665),
 ('PERSON', 'McDonald', 0.6011390084587678),
 ('PERSON', 'Steve Easterbrook', 1.62707021179198),
 ('PERSON', 'McDonald', 0.7252897014392439),
 ('MISC', 'Turnaround Summit', 0.5459067014161887),
 ('PERSON', 'McDonald', 0.733597056118872),
 ('PERSON', 'McDonald', 0.5221199692486291),
 ('LOCATION', 'San Diego', 1.4569853574876104),
 ('PERSON', 'John Gordon', 1.4067061157394036),
 ('PERSON', 'McDonald', 0.6262266486680956),
 ('PERSON', 'McDonald', 0.5300773536597632),
 ('LOCATION', 'U.S.', 1.3314469880747613),
 ('PERSON', 'McDonald', 0.6102694086803659),
 ('PERSON', 'Paul Shapiro', 1.8008827543760988),
 ('LOCATION', 'United States', 1.1536681812718963),
 ('ORGANIZATION', 'McDonald', 0.7478091010431832),
 ('PERSON', 'Shapiro', 1.1529211339569105),
 ('ORGANIZATION', 'Chipotle', 0.27411100096279334),
 ('ORGANIZATION', 'Sofritas', 0.20042503949162985),
 ('PERSON', 'Denny', 1.0445957119600875),
 ('PERSON', 'Johnny Rockets', 0.6257758817370944),
 ('LOCATION', 'White Castle', 0.550052599194086),
 ('ORGANIZATION', 'McDonald', 0.5866372774064789),
 ('PERSON', 'McDonald', 0.6089171335562328),
 ('PERSON', 'Shapiro', 1.4221506683701266),
 ('ORGANIZATION', 'Chicago Tribune', 0.5300056649547958),
 ('PERSON', 'Easterbrook', 1.3357314682060835),
 ('PERSON', 'McDonald', 0.5254242850102231),
 ('MISC', 'burger', 0.20863861829526598),
 ('PERSON', 'McDonald', 0.6882332877969929),
 ('LOCATION', 'U.S.', 1.152526189418561),
 ('PERSON', 'Robert Reich', 1.3686463530945003),
 ('LOCATION', 'U.S.', 0.9064906053018911),
 ('PERSON', 'Clinton', 0.8424408210970944),
 ('PERSON', 'McDonald', 0.8099967902497076),
 ('PERSON', 'McDonald', 0.5726923125964373),
 ('PERSON', 'Laura Ries', 1.2960758120524078),
 ('ORGANIZATION', 'Ries & Ries', 0.8948838138088949),
 ('LOCATION', 'Atlanta', 1.4866648917001795),
 ('PERSON', 'McDonald', 0.7071161079471816)]

This means that out of the 16 times McDonald's occurred, it was tagged as a PERSON 14 times and as an ORGANIZATION 2 times.

MITIE very often does quite well from what I've seen. There seem to be some major companies though for which it doesn't. I know that we can train our own models using MITIE, but it just seems like it should work for one of the most prolific companies of our time (Amazon) and a company as prevailent as McDonald's. I don't think the problem is a training/inference domain mismatch since the English section of the CoNLL 2003 NER task was a Rueters corpus and I'm applying it to news wire. Beyond training my own model, all I can think to do is find these cases MITIE gets terribly wrong and create custom rules that are used to change the output of the NER. Do you have any other suggestions?

**Comment by davisking** [comment]
It should just be a matter of producing a good training dataset.  We would make the training datasets public to make retraining easier but their licenses prevent that.  If building or buying appropriate training data isn't going to be reasonable for you then the best thing to do is as you say just include some additional rules or post processing.

**Comment by AWNystrom** [comment]
Thanks, Davis. Where would you recommend getting labeled data from? Paying
for it is an option.

**Comment by davisking** [comment]
We used the CoNLL 2003 NER task data along with some of the ACE 2008 data.  The CoNLL data is the most useful though so that's what I would mainly focus on.

**Comment by AWNystrom** [comment]
What data was the free model trained on?

**Comment by davisking** [comment]
CoNLL and ACE :)

**Comment by AWNystrom** [comment]
Oh I thought you were saying that training on more data could improve performance and I should try CoNLL and ACE, but if that's what the free model was trained on, how will this improve performance? The results I showed were from the free model. I could be missing something though as I've been awake for 21 hrs.

**Comment by davisking** [comment]
You would add whatever cases you personally care about to CoNLL and then train on the whole thing.

**Comment by AWNystrom** [comment]
Was the free model not trained on the whole thing? I care about people, orgs, and locations, so all but misc.

**Comment by arjunmajum** [comment]
Andrew,

Let me jump in here.

I think what Davis is suggesting is that if you are able to purchase a
dataset like CoNLL (preferably) or ACE. You could train a general purpose
model. If you used both the model would be exactly the same as the free
model we provide.

Now if your particular situation require a special entity such as Amazon to
be recognized more reliably as an Organization, you would simply hand label
a bunch of training examples where that was the case. You would then add
those training examples to the dataset you purchased and train on the
combination of the two. You would then have a model that had good general
purpose performance and the specific performance charecteristics you were
looking for.

Arjun

**Comment by AWNystrom** [comment]
Arjun, thanks for seeing past the confusion and clarifying that. So the
license of the data doesn't restrict the distribution of a model trained on
it, only the data itself. I'll probably go with your suggestion.
