### ISSUE TITLE
getting error after successful compilation

### ISSUE THREAD

**Issue by ankitarath2011** [mit-nlp/MITIE#150]
Hi,

I have installed mitie using the cmake commands. It was successful.

But when I am running the examples I am getting following error. I am using Python 2.7 64 bit in windows 10.

`Traceback (most recent call last):
  File "C:\Users\ankita.a.rath\Downloads\MITIE-master\examples\python\categorize_text.py", line 15, in <module>
    from mitie import *
  File "C:\Users\ankita.a.rath\Downloads\MITIE-master\examples\python/../../mitielib\mitie.py", line 36, in <module>
    _f = ctypes.CDLL(most_recent)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application`

Please help.

**Comment by davisking** [comment]
You have to compile in 64bit mode if you want to use it with a 64bit python.  You do this by telling cmake which visual studio you want to use, e.g. `cmake -G "Visual Studio 14 2015 Win64" ..`

**Comment by davisking** [comment]
The important bit is saying Win64

**Comment by ankitarath2011** [comment]
Thanks. That issue is resolved. But getting one more error.

`Traceback (most recent call last):
  File "C:\Users\ankita.a.rath\Downloads\MITIE-master\examples\python\train_relation_extraction.py", line 17, in <module>
    ner = named_entity_extractor("../../MITIE-models/english/ner_model.dat")
  File "C:\Users\ankita.a.rath\Downloads\MITIE-master\examples\python/../../mitielib\mitie.py", line 247, in __init__
    raise Exception("Unable to load named entity extractor from " + to_default_str_type(filename))
Exception: Unable to load named entity extractor from ../../MITIE-models/english/ner_model.dat
>>> 
`

Can you please help on this.

**Comment by davisking** [comment]
Download the ner_model.dat file.  There are links on the MITIE front page.

**Comment by ankitarath2011** [comment]
Thanks a lot. That issue is resolved. 
One more thing. Do I have to always add mitielib in sys.path in my code? I have added it in system env variable path. But when I am importing it is saying no module mitie. It is working once I am adding the path in sys.path.

**Comment by davisking** [comment]
There are a lot of ways to permanently add things to the pyhton path.  None of them are MITIE specific.  I would look up a few and pick one you like.

**Comment by SyrusBG** [comment]
> You have to compile in 64bit mode if you want to use it with a 64bit python. You do this by telling cmake which visual studio you want to use, e.g. `cmake -G "Visual Studio 14 2015 Win64" ..`

Encountered the error below, and installing cmake and assigning which visual studio fixed my problem! Thank you!
c:\python\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application
