### ISSUE TITLE
Availability of 'pure' model for improved concurrency with NER?

### ISSUE THREAD

**Issue by andymcm** [mit-nlp/MITIE#155]
I'd like to reduce memory usage when doing NER on multiple threads concurrently (Java).  It seems there is a mechanism to support loading of a 'pure' NER model separately from the total word feature model.   If I understand this correctly, I should be able to load the total word feature model once and use it concurrently across threads, while only having to duplicate the (relatively small) pure NER model on each thread.   Is that understanding correct?

If so, are there any pure NER models available to download?  If not, is there a way to extract them from the standard NER models (e.g. ner_model.dat) or do I need to build them from scratch? 

Thanks

Andy

**Comment by davisking** [comment]
No, you can't do that.  See
https://github.com/mit-nlp/MITIE/blob/master/mitielib/include/mitie/total_word_feature_extractor.h#L28

**Comment by andymcm** [comment]
Ah ok, thanks for the response.
