### ISSUE TITLE
What does this file contain - total_word_feature_extractor.dat 

### ISSUE THREAD

**Issue by akshay-vaidya** [mit-nlp/MITIE#157]
What does the MITIE file - total_word_feature_extractor.dat actually contain. I am trying to understand how this library is integrated with Rasa.ai 
Thanks!

**Comment by davisking** [comment]
It contains a dlib::total_word_feature_extractor object.

**Comment by Griffintaur** [comment]
Let's say I want to train MITIE for another language. so that it can be plugged into RASA.
Does it only need the data corpus of the language?
Can someone point out the steps to generate total_word_feature_extractor.dat for that language?
I couldn't find any documentation for that
