### ISSUE TITLE
Updating a trained model

### ISSUE THREAD

**Issue by developer-rakeshpaul** [mit-nlp/MITIE#16]
Hi Team,

Could you please help me how to update a saved model with new training data? Do I have to run the entire trained samples along with the new samples to through a trainer and create a new model for updating an existing model? I tried serializing the trainer and reuse it. However since there are pointer references, I am not able to save the trainer. I am trying to periodically update my model with new samples.

Kind Regards,
rp

**Comment by arjunmajum** [comment]
rp,

Currently you will need to retrain the model using all the training data as you acquire new samples.

It also sounds like you are having trouble with serialization...

To train and save a model follow the approach taken in  'examples/cpp/train_ner/train_ner_example.cpp' through line 106 where the model is saved to disk.

To use a model that you have previously saved follow the approach taken in 'examples/cpp/ner/ner_example.cpp.' Line 60 shows how to read a model from disk.

cheers,

Arjun

**Comment by developer-rakeshpaul** [comment]
Hi Arjun,

Sorry for delaying in replying. Thanks for the inputs and it clarifies my question.

Kind Regards,
rp
