### ISSUE TITLE
Build for Java successful, but no javamitie/jar file

### ISSUE THREAD

**Issue by jeffThompson** [mit-nlp/MITIE#162]
After some wrangling, I got CMake to compile for Java without error, but I don't get any `javamitie` or jar files.

```
java: $ cmake --build . --config Release --target install
[ 78%] Built target dlib
Scanning dependencies of target mitie
[100%] Built target mitie
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libmitie.dylib
-- Up-to-date: /usr/local/include/mitie.h
```

(On a Mac, running CMake 3.5.2, swig 3.0.7)

**Comment by davisking** [comment]
Follow the instructions on the front page: https://github.com/mit-nlp/MITIE

It doesn't look like you followed them.  Here is what they say:

> There is an example Java program in the examples/java folder. Before you can run it you must compile MITIE's java interface which you can do like so:
> 
> cd mitielib/java
> mkdir build
> cd build
> cmake ..
> cmake --build . --config Release --target install

**Comment by jeffThompson** [comment]
@davisking – maybe I didn't explain well. I ran all the commands to compile (like you pasted above), and it did everything without any errors. But the instructions say it should `place a javamitie shared library and jar file into the mitielib folder` but I don't see a jar file created anywhere.

**Comment by davisking** [comment]
The output you pasted shows that you ran the mitie build script, not the javamitie build script.  If you typed the commands I pasted you would have run the _**javamitie**_ build, not _**mitie**_.

**Comment by jeffThompson** [comment]
I don't know, I did run those commands exactly. I made a `build` folder in the `java` folder (not the examples one, the one in `mitielib`. I cd'd into the `build` folder and ran the two `cmake` commands.

I'll try deleting and re-downloading everything (maybe I messed up a cmake file somewhere along the way) but I'm sure I'm following the instructions.

**Comment by davisking** [comment]
You must have accidentally invoked the cmake command on the mitielib folder rather than the mitielib/java folder.

**Comment by jeffThompson** [comment]
[groan] yep, totally. I was getting a ton of errors and trying too many different things. This is what I get for working on this late at night. Sorry about that!
