### ISSUE TITLE
Is there any distributed version?

### ISSUE THREAD

**Issue by jxg972** [mit-nlp/MITIE#163]
number of raw ASCII files found: 513
num words: 200000
saving word counts to top_word_counts.dat
number of raw ASCII files found: 513
Sample 50000000 random context vectors
Now do CCA (left size: 50000000, right size: 50000000).
std::bad_alloc

We use clusters, and max RAM of a single machine is only 64G.It rans out of memory everytime.Is there any distributed version?

**Comment by davisking** [comment]
No, there is just the one version.
