### ISSUE TITLE
Do you also consider supporting python 3.X?

### ISSUE THREAD

**Issue by jenniferzhu** [mit-nlp/MITIE#164]
As more and more users migrate to python 3, is mitie possible to support python 3?

**Comment by davisking** [comment]
Lots of people use MITIE with python 3.  Are you having some issue?

**Comment by nacyzhaomin** [comment]
i want mitie migrate to python3, so what should i do. i see the document it support python2,7..thx.

**Comment by davisking** [comment]
You shouldn't have to do anything.  Like I said, MITIE works with python 3.  Is there some issue?
