### ISSUE TITLE
Zero entries in the feature vector

### ISSUE THREAD

**Issue by svazzole** [mit-nlp/MITIE#169]
Hi.
I've trained the feature extractor on wikipedia (italian) as suggested. I have noticed that, when I give a sentence as input to the featurizer, it is represented as a 271 dimensional vector where all the features fom 1st to 180th are zero (almost in every sentence i tested). Is there a specific reason for this behaviour or is something that I messed up?

**Comment by davisking** [comment]
Give it words, not sentences.  That's why it's zero.

**Comment by svazzole** [comment]
Ok. Thanks for you response. So if I want to see how a sentence is represented, should I call the tokenizer and then take the mean of the vectors?

**Comment by davisking** [comment]
Yes, that would be a fine thing to do.

**Comment by svazzole** [comment]
Thanks a lot for your help. I think I can close the issue.
