### ISSUE TITLE
tokenising misaligned for java strings?

### ISSUE THREAD

**Issue by mjl67** [mit-nlp/MITIE#17]
Hi,

I am observing some misalignment of the token indexing when calling Java method edu.mit.ll.mitie.mitie.tokenizeWithOffsets with a string containing multi-byte characters. For example, calling it with the string `funny “quotation marks” and so on` produces tokens:
```
Token 0: index=0, value=<funny>
Token 1: index=6, value=<“quotation>
Token 2: index=19, value=<marks”>
Token 3: index=28, value=<and>
Token 4: index=32, value=<so>
Token 5: index=35, value=<on>
```
Note that the quotation marks are Unicode 201c and 201d. token 2's index (19) is out by 2 (it should be 17), and token 3's (28) is out by 4 (it should be 24). So there appear to be cumulative indexing errors when "multi-byte" characters are encountered.

**Comment by davisking** [comment]
This is by design.  MITIE does everything using UTF-8 and those offsets are
the reported byte offsets into the UTF-8 strings.  If you want to know the
character offset then you need to use a routine that converts from UTF-8
byte positions into character counts.

Cheers,
Davis
