### ISSUE TITLE
Does MITIE support Python 3.6.3?

### ISSUE THREAD

**Issue by lzhao7812** [mit-nlp/MITIE#170]
Hello, 

I need to use Python 3.6.3 for another python library on Windows, so just wondering if MITIE supports Python 3 and if not, how difficult is it to support it? Thanks!

**Comment by davisking** [comment]
It should work just fine in python 3.

**Comment by lzhao7812** [comment]
I saw in the setup.py, it specifies only upto 3.5, but not 3.6. Is it possible to update it to 3.6 so that it can be installed out of box?

**Comment by davisking** [comment]
Did you get an error when trying to use MITIE with python 3.6?

**Comment by lzhao7812** [comment]
Yes, here is the error:

Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\xxx\appdata\local\temp\pip-1rcpzr_z-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
    Complete output from command c:\users\xxx\envs\venv-win-rasa\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-1rcpzr_z-build\\setup
.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\linzhao\AppData\Local\Temp\pip-5uwba90y-
record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\xxx\envs\venv-win-rasa\include\site\python3.6\mitie:
    running install
    running build
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\users\linzhao\envs\venv-win-rasa\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\linzhao\\AppData\\Local\\Temp\\pip-1rcpzr_z-build\\setup.py';f=getattr(tokenize,
 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\linzhao\AppData\Local\Temp\pip-5uwba90y-record\install-record.tx
t --single-version-externally-managed --compile --install-headers c:\users\linzhao\envs\venv-win-rasa\include\site\python3.6\mitie" failed with error code 1 in C:\Users\linzhao\AppData\Local\Temp\pip-
1rcpzr_z-build\

**Comment by davisking** [comment]
Don't use setup.py.  Follow the instructions for us on windows as they appear in the README.

**Comment by huyue8921** [comment]
Python 3.6.4
pip install git+https://github.com/mit-nlp/MITIE.git
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\huyue\appdata\local\temp\pip-yn_8mo_z-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
Exception:
Traceback (most recent call last):
  File "d:\localsdk\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\localsdk\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\localsdk\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "d:\localsdk\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "d:\localsdk\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "d:\localsdk\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "d:\localsdk\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

**Comment by liuyue94** [comment]
sorry  ,I want to install mitie on my win7 system ,but I also encountered the above error. I have  tried so many times ,but It does not work，so i want to know whether you have  solved this problem , please help me ,thank you very much

**Comment by davisking** [comment]
The readme contains instructions for installing on windows. Don’t use setup.py. Use those instructions.

**Comment by davisking** [comment]
That's not what the instructions say to do.  But in any case, I just updated the setup.py so it supports windows.  So try running that same command you ran again, it should work now.

**Comment by saravananpsg** [comment]
Thank you Davis for making it easy.  I have tried the pip install for python 3.6 on my windows 10 and installed the package successfully.

Also, I have used the following option:

parent = os.path.dirname(os.path.realpath(__file__)) 

---use this for python 3.6--
parent  = os.path.abspath(os.path.dirname(sys.argv[0]))

**Comment by davisking** [comment]
You don't have to setup the path to the mitie dll if you run setup.py.

**Comment by MaryFllh** [comment]
Hello 
I'm using python 3.6 and tried running the text_categorizer_pure_model.py but raises an attribute error when loading the trained model using text_categorizer() :
line 719, in __del__
    self.__mitie_free(self.__obj)
AttributeError: 'text_categorizer' object has no attribute '_text_categorizer__obj'
However, the code runs perfectly fine on python 2.7. 
Is there any solution to this?

**Comment by davisking** [comment]
The fix for this is live on github now.
