### ISSUE TITLE
wordrep tool reference

### ISSUE THREAD

**Issue by juncaofish** [mit-nlp/MITIE#172]
A great library you created. A question on wordrep tool, how is word vector extracted from the trained doc? Is each word vector obtained by words around it in a fixed window?  Is there any paper for reference?

**Comment by davisking** [comment]
It's basically this: https://arxiv.org/pdf/1206.6403.pdf but with the
addition of word morphology.

**Comment by juncaofish** [comment]
Thanks a lot.
