### ISSUE TITLE
error: [WinError 2] The system cannot find the file specified  Error in installing

### ISSUE THREAD

**Issue by gauravjain024** [mit-nlp/MITIE#175]
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\gaurav~1.jai\appdata\local\temp\pip-7ri68ct1-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
    Complete output from command c:\users\gaurav.jain\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\GAURAV~1.JAI\\AppData\\Local\\Temp\\pip-7ri68ct1-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\GAURAV~1.JAI\AppData\Local\Temp\pip-133invae-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\users\gaurav.jain\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\GAURAV~1.JAI\\AppData\\Local\\Temp\\pip-7ri68ct1-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\GAURAV~1.JAI\AppData\Local\Temp\pip-133invae-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GAURAV~1.JAI\AppData\Local\Temp\pip-7ri68ct1-build\

**Comment by davisking** [comment]
Follow the instructions on the front page of MITIE.
