### ISSUE TITLE
Unable to create ner_trainer based on ..

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mit-nlp/MITIE#176]
Ubuntu 16.04
MITIE 0.2.0

Hi guys I have come back to a project that implemented MITIE however I am now receiving an error:

Unable to create ner_trainer based on ../MITIE-models/english/total_word_feature_extractor.dat

I have reinstalled using the instructions in the readme, additionally reinstalled using pip / pip3 the file total_word_feature_extractor.dat exists, cannot get the program working at all. I have added the path for mitielib and tried in python 2.7 and 3.5, no matter what I change I keep receiving this same error.

Any suggestions on what could be the issue ? Using the example instead of my previous program also fails with the same error.

**Comment by davisking** [comment]
Fill out the issue template

**Comment by AdamMiltonBarker** [comment]
I re downloaded MITIE-models and replaced the ones I had and all works now
