### ISSUE TITLE
Bad Allocation when number of words exceed 21000

### ISSUE THREAD

**Issue by cmllmrnn** [mit-nlp/MITIE#179]
## Expected Behavior

I've read that running wordrep with big datasets is fine although it will take a long time. I ran a small text file [ofrcorpus176.txt](https://github.com/mit-nlp/MITIE/files/1918327/ofrcorpus176.txt) and it succeeded. 

## Current Behavior

I am running wordrep  and it outputs the .dat files after the process is finished when the number of words is less than 21000. However, for bigger data, it says "bad allocation" usually after stating the number of raw ASCII found or after CCA.

For instance:
number of raw ASCII files found: 283
num words: 21616
saving word counts to top_word_counts.dat
number of raw ASCII files found: 283
bad allocation

## Steps to Reproduce

I tried to train the French corpus [here](https://github.com/nicolashernandez/free-french-treebank/tree/master/130612/frwikinews/txt) [frwikinews-20130110-pages-articles.txt](https://github.com/mit-nlp/MITIE/files/1918319/frwikinews-20130110-pages-articles.txt)
with a size of only 13MB. It contains 80055 words but this happened:

number of raw ASCII files found: 1
num words: 80055
saving word counts to top_word_counts.dat
number of raw ASCII files found: 1
Sample 50000000 random context vectors
Now do CCA (left size: 2487430, right size: 2487430).
bad allocation

* **Version**: 0.5
* **Where did you get MITIE**: Downloaded from https://github.com/mit-nlp/MITIE
* **Platform**: Windows 10 64-bit 7GB RAM Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz 2.39GHz 
* **Compiler**: wordrep exe file ran in command prompt

**Comment by davisking** [comment]
You need to use a computer with more RAM.

**Comment by davisking** [comment]
The only solution is more ram. Use a machine with 64gb or 128gb. Ram is really cheap.

**Comment by cmllmrnn** [comment]
Hi, I'm now using a 160GB RAM but it still says bad allocation for 4GB, 1GB, 340MB and even 13MB data. My machine has 40 vCPU. Any machine specifications aside from the RAM?

**Comment by cmllmrnn** [comment]
Thanks. That seems to resolve it but I have another problem. Now, every time I run large data, it crashes. 

"wordrep.exe has stopped working. A problem caused the program to stop working correctly. Please close the program"

I'm using Windows 10 and I enabled compatibility mode for Windows 8 in the Properties dialog box and ran Command Prompt and wordrep as admin. Do I need to do anything else?

**Comment by davisking** [comment]
Don't modify anything in the build project or how you run it. Just run it normally.  It should run just fine.

**Comment by cmllmrnn** [comment]
Yup at first I didn't modify anything. But because it crashed for 300MB+ data, I searched Google for fixes assuming it's a generic problem but those didn't do the trick.
