### ISSUE TITLE
Is there a Citiation I can give?

### ISSUE THREAD

**Issue by mdda** [mit-nlp/MITIE#18]
I'm currently writing a paper, and I'd like to include a reference to the MITIE system.  However, there's no mention of it on the CSAIL (?) site, nor any author names, etc.

Can you suggest a paper or technical report that I could cite? - it would be very helpful (and possibly good for the authors too).

All the Best (and thank you for releasing such excellent software)
Martin
:-)

**Comment by davisking** [comment]
There isn't any paper specifically about MITIE.  However, since MITIE is basically just a thin wrapper around dlib I would cite dlib's JMLR paper: http://dlib.net/faq.html#HowcanIcitedlib

Thanks, I'm glad you like it :)

**Comment by livyreal** [comment]
actually, we saw people using a wrong citation to MITIE.
https://www.aclweb.org/anthology/W17-5522.pdf
https://link.springer.com/content/pdf/10.1186/s13321-018-0327-2.pdf

Geyer, K., Greenfield, K., Mensch, A. C., and Simek, O. (2016). Named entity recognitionin 140 characters or less. In# Microposts, pages 78–7 

May be the case to contact the authors or leave this information (to cite dlib) highlighted.
