### ISSUE TITLE
Generating total_word_feature_extractor.dat for different language

### ISSUE THREAD

**Issue by Griffintaur** [mit-nlp/MITIE#181]
Let's say I want to train MITIE for another language. so that it can be plugged into RASA.
Does it only need the data corpus of the language?
Can someone point out the steps to generate total_word_feature_extractor.dat for that language which is need for RASA for using MITIE as backend?
I couldn't find any documentation for that

**Comment by davisking** [comment]
There are instructions here: https://github.com/mit-nlp/MITIE/blob/master/examples/python/train_ner.py
