### ISSUE TITLE
unable to run the wordrep command

### ISSUE THREAD

**Issue by Griffintaur** [mit-nlp/MITIE#182]
I am unable to run the command: wordrep -e /home/dataFolders/
It gives an error whenever I invoke this:
wordrep command not found

PS: /home/dataFolders/ contains all the text files of my language

**Comment by davisking** [comment]
Your computer doesn't have the wordrep executable.  "command not found" means it's not on your computer.  You can't run a program if it's not on your computer.

You need to go into the wordrep folder and compile it.  Use cmake to do so.
