### ISSUE TITLE
The wordrep tool needs user input to finish training

### ISSUE THREAD

**Issue by McWillie** [mit-nlp/MITIE#184]
## Expected Behavior
I'm using the wordrep tool to train a custom feature extraction model for a new language.
It runs as expected _except_ that after logging `Now do CCA` to terminal it requires user input (hitting Enter) to continue. Expected behavior would be running from start to finish without needing any user intervention. This is very painful for those of us who have to resolve to training our models in the cloud.

## Current Behavior
The wordrep tool requires user input to finish training a model.

## Steps to Reproduce
Run wordrep with a corpus:
`wordrep -e <folder containing only text files>`

* **Version**: 0.5.0
* **Where did you get MITIE**: git clone of MITIE master branch
* **Platform**: Windows Server 2012 64bit (AWS instance)
* **Compiler**: cmake, version 3.12.0-rc1

**Comment by davisking** [comment]
Uh, you sure about that?

**Comment by McWillie** [comment]
It did advance only after taking an unexpected amount of time (I have one other training session to compare with from somebody else), dropping resource use in comparison with when CCA was initiated _and_ immediately after I provided user input so a coincidence would be very unlikely. I'm not implying that it's necessarily a bug or that it's designed to be in the code, this was just my experience.

**Comment by davisking** [comment]
Well, there isn't any code in MITIE that pauses for user input.

**Comment by McWillie** [comment]
Alright, I'll have to look elsewhere then.
Thank you for the work and speedy replies!
