### ISSUE TITLE
Build of libmitie.so fails on Windows with Mingw-Win64

### ISSUE THREAD

**Issue by davesomebody** [mit-nlp/MITIE#185]
So I wanted to build on Windows 10 with Mingw-W64 and encountered an error linking libmitie.so.

## Expected Behavior
I expected it to link libmitie.so

## Current Behavior
Linking libmitie.so
../dlib/dlib/misc_api/misc_api_kernel_1.o:misc_api_kernel_1.cpp:(.text+0x78a): undefined reference to `__imp_timeGetTime'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [makefile:52: libmitie.so] Error 1

## Steps to Reproduce
Grab the MIngw-W64, open up the Mingw-W64 terminal from the start menu.  Unzip mitie v 0.5 

I cd into MITIE-0.5\mitielib and run mingw32-make

<lots of stuff compiles>

Linking libmitie.so
../dlib/dlib/misc_api/misc_api_kernel_1.o:misc_api_kernel_1.cpp:(.text+0x78a): undefined reference to `__imp_timeGetTime'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [makefile:52: libmitie.so] Error 1

I overcame this by changing the ld statement in the makefile to say:
@$(CC) -shared $(OBJ) $(BLAS) -lwinmm -o $@

* **Version**: MITIE 0.5
* **Where did you get MITIE**: https://github.com/mit-nlp/MITIE/releases
* **Platform**: Wndows Vesion 10, 64-bit
* **Compiler**: x86_64-8.1.0-posix-seh-rt_v6-rev0

**Comment by davisking** [comment]
To compile MITIE on windows you are supposed to use CMake. The makefiles
are only for unix systems.

**Comment by davesomebody** [comment]
Thanks for the prompt reply.  I'll have to try CMake next time I guess.  I figured since I'm more familiar with old fashioned Make I would give that a shot.
