### ISSUE TITLE
[Documentatio] train-ner script

### ISSUE THREAD

**Issue by stefan-it** [mit-nlp/MITIE#19]
Hi,

using the `ner_conll` example I found the `train-ner` script in `MITIE/tools/ner_conll/train-ner`:

```bash
./ner --train-chunker eng.train_all_some_sentences_combined $THREADS > $LOG
    ./ner --train-id      eng.train_all_some_sentences_combined $THREADS >> $LOG

    ./ner --test-id eng.testb >> $LOG
    ./ner --tag-conll-file ner_model.dat eng.testb | ./conlleval 
    echo $LOG
```

As I cannot find a executable called "ner" - I'm just wondering if it should be `train-ner` instead, but the `train-ner` command line arguments only provides:

```cpp
parser.add_option("h", "Display this help information.");
        parser.add_option("train", "train named_entity_extractor on CoNLL data.");
        parser.add_option("test", "test named_entity_extractor on CoNLL data.");
        parser.add_option("threads", "Use <arg> threads when doing training (default: 4).",1);
        parser.add_option("tag-conll-file", "Read in a CoNLL annotation file and output a copy that is tagged with a MITIE NER model.");
``` 

See `MITIE/tools/ner_conll/src/main.cpp`.

So my question is if that small `train_ner` script should be updated then?

Thanks in advance (+ I'm really looking forward to train a model for German),

Stefan

**Comment by davisking** [comment]
The train-ner script you found is in the same folder as the ner program.  Also, to train a german model you will have to use the wordrep program to train a german word model before doing any entity extraction training.
