### ISSUE TITLE
attribute error when running on python3.6

### ISSUE THREAD

**Issue by MaryFllh** [mit-nlp/MITIE#196]
If you are reporting a bug or problem with MITIE then fill out the entire template below.  Issues asking questions about why something doesn't work that fail to fill out the entire template will be closed.

Also, **the issue tracker is not a code writing service, do not ask for someone to write code for you.**  In particular, do not submit issues asking for feature improvements to the example programs.  The examples are documentation, their purpose is to teach, not to be useful programs.  **If there is some feature improvement you want in an example program then it's up to you to write it**.  

If you aren't reporting a bug or problem with MITIE then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get MITIE**: 
* **Platform**: 
* **Compiler**:

**Comment by MaryFllh** [comment]
Hi
I'm trying to run text_categorizer_pure_model on python 3.6, but an attribute error is raised when loading the trained model using text_categorizer():
line 719, in __del__
    self.__mitie_free(self.__obj)
AttributeError: 'text_categorizer' object has no attribute '_text_categorizer__obj'
The code runs perfectly fine on python 2.7.
Is there a solution to this?

**Comment by nicola88** [comment]
I have the exact same error on Ubuntu Server 16.04 using MITIE 0.5 / 0.6 and Python 3.5.2 / 3.6.6.

**Comment by MaryFllh** [comment]
Thank you very much. It is working now.
