### ISSUE TITLE
What are the Wordrep Parameters to improve the vectors model 

### ISSUE THREAD

**Issue by shanalikhan** [mit-nlp/MITIE#197]
I am trying to run the `wordrep` on 8K documents.

```
./wordrep -e /foldername
```

I want to know how i can improve the model ? Which parameters can be used in wordrep to improve the model.
No matter how much time it takes. Needs to improve the feature vectors for it.

**Comment by davisking** [comment]
MITIE is purposefully designed to have no parameters.  The thing that will make this work better is using more training data.  If you want to use lower level tooling that lets you design your own models then you should look at dlib, since MITIE is a thin wrapper around dlib.

**Comment by shanalikhan** [comment]
alright, do you have any published research paper available that shows the state-of-the-art `wordrep` algo and technique behind it. That would be great ?

**Comment by davisking** [comment]
It's based on this method: http://jmlr.csail.mit.edu/papers/volume16/dhillon15a/dhillon15a.pdf
