### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by Jordon15** [mit-nlp/MITIE#206]
If you are reporting a bug or problem with MITIE then fill out the entire template below.  Issues asking questions about why something doesn't work that fail to fill out the entire template will be closed.

Also, **the issue tracker is not a code writing service, do not ask for someone to write code for you.**  In particular, do not submit issues asking for feature improvements to the example programs.  The examples are documentation, their purpose is to teach, not to be useful programs.  **If there is some feature improvement you want in an example program then it's up to you to write it**.  

If you aren't reporting a bug or problem with MITIE then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get MITIE**: 
* **Platform**: 
* **Compiler**:

**Comment by Jordon15** [comment]
expected: a mitie prompt or some indication that mitie is running from the terminal, proper installation is rest assured, installed from akami bin by Homebrew do I enter examples into the terminal? Basic commands would be nice as documentation hoping I have the dlib documentation to work with as a command library. current: bash does not recognize make as a command Reproduce: Last login: Thu Jan 16 00:17:21 on ttys001
Chriss-MacBook-Pro:~ chrislong$ MITIE_EXPORT char* mitie_load_entire_file (
-bash: syntax error near unexpected token `('
Chriss-MacBook-Pro:~ chrislong$ 

.....

**Last login: Thu Jan 16 00:21:31 on ttys001
Chriss-MacBook-Pro:~ chrislong$ cat Tap a key.txt | ./ner_stream MITIE-models/english/ner_model.dat

-bash: ./ner_stream: No such file or directory
cat: Tap: No such file or directory
cat: a: No such file or directory
cat: key.txt: No such file or directory
Chriss-MacBook-Pro:~ chrislong$ 


Mabie I should stick to awk and sed and columns.

**

**Comment by davisking** [comment]
Please fill out the issue template.

**Comment by Jordon15** [comment]
Expected Behavior: Some sort of API
Current Behavior: command not found
Steps to Reproduce: enter makefile in the terminal, open makefile 
Version: most recent github commit
Where did you get MITIE: github, homebrew install 
Platform: High Sierra 10.13.6
Compiler: IDK

**Comment by Jordon15** [comment]
API or GUI? if it's all from terminal should be good just searching for commands the system will recognize.
