### ISSUE TITLE
running face detection example ERROR

### ISSUE THREAD

**Issue by chfakht** [mit-nlp/MITIE#21]
Hi , when trying to run face_detection.cpp
by g++ -o output -lpng -ljpeg -O3 -I.. ../dlib/all/source.cpp -lpthread -lX11 face_detection_ex.cpp
./output test.jpg
exception thrown!
Unable to load image in file test.jpg.
You must #define DLIB_PNG_SUPPORT and link to libpng to read PNG files.
Do this by following the instructions at http://dlib.net/compile.html.

the instructions was not clear for me
Note also that if you want to work with jpeg/png files using dlib then you will need to link your program with libjpeg and/or libpng. You also need to tell dlib about this by defining the DLIB_JPEG_SUPPORT and DLIB_PNG_SUPPORT preprocessor directives.

i have installed libjpeg and libpng and added the flags ... but can"t figure out what's wrong

**Comment by davisking** [comment]
This is offtopic for the MITIE project.  But you should use cmake to compile your project if you don't know how to use gcc.
