### ISSUE TITLE
PHP bindings

### ISSUE THREAD

**Issue by ankane** [mit-nlp/MITIE#216]
Hi @davisking, hope you're doing well. Just wanted to let you know I released [PHP bindings](https://github.com/ankane/mitie-php) as well (in addition to Ruby). It only supports NER right now, but should be easy to add the other APIs as needed.

Thanks again for this great project!

**Comment by davisking** [comment]
Sweet.  I just updated the README to link to the PHP bindings :)

**Comment by ankane** [comment]
Great, thanks!
