### ISSUE TITLE
One or two output examples in the README.md file

### ISSUE THREAD

**Issue by holgerd77** [mit-nlp/MITIE#23]
MITIE library makes a really exciting impression at first glance. However it would be very helpful if you could provide one or two examples of what the library actually outputs when being used on a text. Especially for people like me not totally into language processing it is hard to get a clear picture of what the library actually does and what it can be used for.

Cheers
Holger

**Comment by davisking** [comment]
It comes with example programs that do this, look in the examples folder.
There are also the two release announcements on the dlib blog that explain
it as well.
http://blog.dlib.net/2014/04/mitie-completely-free-and-state-of-art.html
http://blog.dlib.net/2014/07/mitie-v02-released-now-includes-python.html

**Comment by holgerd77** [comment]
Ah, very cool, would be helpful if you link these two blog articles also in the GitHub README.md.

**Comment by davisking** [comment]
No problem.
