### ISSUE TITLE
Sourceforge considered harmful

### ISSUE THREAD

**Issue by sethwoodworth** [mit-nlp/MITIE#24]
Sourceforge has a troubling history of [hijacking projects](http://seclists.org/nmap-dev/2015/q2/194) and should be considered harmful.

Github has arbitrary file downloads associated with releases (git tags).  An admin should be able to add the data download for MITIE to [the repo's releases](https://github.com/mit-nlp/MITIE/releases/tag/v0.4) and away from [Sourceforge](http://sourceforge.net/projects/mitie/postdownload?source=dlp).

**Comment by davisking** [comment]
Yeah, I've moved all the dlib files over to another hosting provider because of this.  We will move the MITIE files over as well in a few days.

**Comment by davisking** [comment]
The files are now hosted on github.
