### ISSUE TITLE
How is score of entity calculated?

### ISSUE THREAD

**Issue by ksindi** [mit-nlp/MITIE#25]
How is the score of the entity calculated? Also, how can one interpret the score?

**Comment by davisking** [comment]
It's the output of a support vector machine.  Positive values mean it's probably an entity and negative values mean it's probably not.  The larger the value the more confident it is.

**Comment by Rajesh-Bhat** [comment]
Is there any way to get scores for all the entity or intents?
Example:
intent1 : confidence value
intent 2 : confidence value

**Comment by sugampandey** [comment]
@davisking - is it possible to get scores for the other intents too, not just the best matching intent?

**Comment by davisking** [comment]
No

**Comment by nsanthanam** [comment]
Is the score returned the signed distance of the entity from the hyperplane? If so, should we expect to see negative scores for tokens that MITIE considers non-named-entities? We have not seen any so far across a large number of examples (in the 1000s).

**Comment by davisking** [comment]
Yes, that's what it is.  No, you will not see non-entities output.
