### ISSUE TITLE
Get Java API by JavaCpp?

### ISSUE THREAD

**Issue by wihoho** [mit-nlp/MITIE#29]
Hello,

This library is really like a dream.

Right now, I need to have Java api to train customized model. So is it possible to provide Java API by using https://github.com/bytedeco/javacpp. 

Thanks.

**Comment by davisking** [comment]
It's possible to add one.  We would use SWIG to do it, just as the current
Java MITIE API does.  However, why don't you want to use the existing
Python training API?  You can load the trained models with the Java API
once training finishes.

**Comment by wihoho** [comment]
Thanks for your reply.

Unfortunately, we are only allowed to use Java in production.

**Comment by davisking** [comment]
The training process can take a fair amount of time to run and also must be
run on a beefy machine.  We generated the existing model files on a 12 core
machine with 128GB of RAM.  Depending on what part of the training process
you run, you could easily consume large fractions of the RAM of such a
machine.  So the training effectively consumes all the resources of a large
server.  It's not the sort of thing I would normally suggest being launched
automatically as part of a larger application.  You certainly could, but
it's resource intensive.  Normally it's best to manually generate the
models on some large workstation and then copy the generated files into
your production system and use the Java APIs.  You will also usually want
to check the accuracy of the generated model and then adjust your training
data annotations or add more depending on the results.  So training is
usually a manual and iterative process.

Given all that, do you still want a Java training API? :)

**Comment by wihoho** [comment]
Hi davisking,

I totally agree with you.

I have some experience with training SVM models using images. The process is slow and consumes a large amount of resources.

But we have very specific cases to deal with, and we are very likely to limit the amount of data to train the model. Still the restriction is that we are only allowed to use Java in production. And we really want to make the whole process automatically,.

If possible, thank you very much. :)

**Comment by wihoho** [comment]
By the way, this is really the best named entity recognition package that I have ever seen.

The speed and accuracy is very impressive. Moreover, it is friendly to commercial usages.

**Comment by davisking** [comment]
Thanks :)

We will add a Java API onto our todo list.

**Comment by davisking** [comment]
There is now a MITIE Java API thanks to this PR https://github.com/mit-nlp/MITIE/pull/32
