### ISSUE TITLE
Custom relationship extraction example in java?

### ISSUE THREAD

**Issue by allenkim67** [mit-nlp/MITIE#30]
I dont see an example for custom relationships in java. Is this supported? How can I learn more about how to use this feature?

**Comment by davisking** [comment]
If you want to train a custom model you can use the Python or C++ API's to
generate the model file.   Then you can use that model file in Java with
the existing Java APIs.

**Comment by davisking** [comment]
There is now a MITIE Java API thanks to this PR https://github.com/mit-nlp/MITIE/pull/32
