### ISSUE TITLE
How to create a svm model ?

### ISSUE THREAD

**Issue by damianoporta** [mit-nlp/MITIE#34]
Hello,
I just have started with MITIE, I would like to understand how can i create a model for binary relationship.
Unfortunately I need italian models so I must create them from scratch. Reading the examples i found a good way to create NER models (here: https://github.com/mit-nlp/MITIE/blob/master/examples/java/TrainNerExample.java)

and here: https://github.com/mit-nlp/MITIE/blob/master/examples/java/NerExample.java for **BinaryRelationDetector**, the problem is how can i create a .svm ? and how can I train it?

Is there a tutorial to understand how can i create a good binary relation model ?

Thank you for your support!

**Comment by davisking** [comment]
Take a look at the python example programs, they show how to do this.
