### ISSUE TITLE
How to make multiple models share the same extractor?

### ISSUE THREAD

**Issue by wihoho** [mit-nlp/MITIE#36]
Hi Davis,

Thanks for your help always. 

We always want to reduce the memory usage. Since normally we can not control extractor, so at least we hope that multiple models can share the same extractor. 

With the current C++ implementation without using pointer, it seems that there is no way to share the extractor among multiple models. I tried to write the following code in three cases.

``` java
TotalWordFeatureExtractor totalWordFeatureExtractor = TotalWordFeatureExtractor.getEnglishExtractor();
NamedEntityExtractor ner = new NamedEntityExtractor(file.getAbsolutePath(), totalWordFeatureExtractor);
```

The above code consumes around 680 MB JVM memory.

``` java
TotalWordFeatureExtractor totalWordFeatureExtractor = TotalWordFeatureExtractor.getEnglishExtractor();
NamedEntityExtractor ner = new NamedEntityExtractor(file.getAbsolutePath(), totalWordFeatureExtractor);
NamedEntityExtractor ner2 = new NamedEntityExtractor(file.getAbsolutePath(), totalWordFeatureExtractor);
```

The above code consumes around 975 MB JVM memory as following.

<img width="532" alt="screen shot 2016-01-09 at 7 47 15 pm" src="https://cloud.githubusercontent.com/assets/1862990/12216930/6516666c-b72c-11e5-9fd3-0042aed4cc43.png">

``` java
TotalWordFeatureExtractor totalWordFeatureExtractor = TotalWordFeatureExtractor.getEnglishExtractor();
NamedEntityExtractor ner = new NamedEntityExtractor(file.getAbsolutePath(), totalWordFeatureExtractor);
NamedEntityExtractor ner2 = new NamedEntityExtractor(file.getAbsolutePath(), totalWordFeatureExtractor);
NamedEntityExtractor ner3 = new NamedEntityExtractor(file.getAbsolutePath(), totalWordFeatureExtractor);
```

The above code consumes around 1.26 GB JVM memory.

For the detailed code, please refer to the following link.
https://github.com/wihoho/MITIE/blob/master/mitielib/java/maven/src/test/java/edu/mit/ll/mitie/NamedEntityExtractorTest.java#L41

Obviously, there is not what we want. The ideal case is that the memory shall still be around 690 MB even there are three different models. So I assume that using pointer in the C++ code will be the only way to overcome this issue. We would like to seek your opinions on resolving this issue because actually we are not good at C++. 

Thank you.

**Comment by davisking** [comment]
Yeah I know what you mean.  However, why don't you train one big model that
predicts all the labels you want to use at once?

**Comment by wihoho** [comment]
Thanks for your reply.

We have different cases to adopt this NER. For instance, one is to extract useful information from flight tickets. Also, there are many other cases. We have concerns on the resources needed if all data is aggregated to train a single model. Moreover, the accuracy may not be guaranteed.

**Comment by davisking** [comment]
I see what you mean.  I'm trying to think of an API that lets you do what
you want but doesn't introduce the opportunity for user error (e.g.
creating a NER object that doesn't have any feature extractor it can use
and exploding when the user invokes it).  The best thing I can think of is
making a new object, micro_ner say, that can be constructed from an
existing ner object.  micro_ner could copy everything in the original
object except for the large feature extractor.  Then when you want to use
the micro_ner instance you need to supply it with text and also with a full
ner object so it can use the feature extractor in it.  How does that
sound?  Does that work for your usecases?

**Comment by wihoho** [comment]
Yeah. That will be great.

**Comment by marghidanu** [comment]
Hello Davis,

I'm having a similar problem where I allow users to create their own models and load them dynamically when changed.  So loading multiple model files can take up some memory (and also it's a bit redundant). If this feature would be available this would be great!

**Comment by davisking** [comment]
It's on my todo list.  It's a long list though :)

**Comment by marghidanu** [comment]
Awsome! Keep up the great work!

**Comment by marghidanu** [comment]
Hello Davis,

From what I see the lastest approved PR (Python pure model persistence), solves our issue. Right? At least for Python users ... :)

**Comment by davisking** [comment]
Right, further API changes are needed to support this.

**Comment by vinvinod** [comment]
Hello Davis,

Please have a look at #88 . 
I was in need of this feature for my code in python. 
I have made the changes which I needed.
Let me know what you think.

**Comment by SakthivelAnand** [comment]
Hello,
I am new to NLP ,i don't know how to configure,i can't uderstand existing instructions , the mitie for java api...Please help me to config it and provide me aexample program for the ner train with File contents
Thank You

**Comment by davisking** [comment]
This is already there.  Look in the examples folder.   Also, the front page
in github tells you what to type to compile mitie.  Read the instructions.

**Comment by SakthivelAnand** [comment]
Thank you David ...I got it...😅👍
