### ISSUE TITLE
What does total_word_feature_extractor.dat contain?

### ISSUE THREAD

**Issue by mahaben** [mit-nlp/MITIE#40]
Hi there,

Can you explain what does otal_word_feature_extractor.dat in MITIE-models contain?

Thanks in advance.

**Comment by davisking** [comment]
It's created by the wordrep program and basically contains word vectors for every English word.

**Comment by mahaben** [comment]
Thanks for your reply! I have another question, actually I want to use the model ner_model.dat in the folder MITIE-models but wants to add other entities. Is it possible?

Thanks again :)

**Comment by aniket-chowdhury** [comment]
You can use rasa_nlu to train your custom model.
