### ISSUE TITLE
Building MITIE java on Windows

### ISSUE THREAD

**Issue by skprasadu** [mit-nlp/MITIE#42]
MITIE is a cool tool and much more focused and  ease of use. I have Cygwin on windows and company restriction is that I cannot have VS.Net..

Can someone guide me how to build it. Thanks in advance.

Krishna

**Comment by davisking** [comment]
Did you try using the instructions in the README?

**Comment by skprasadu** [comment]
Yes as per README it is cmake -G "Visual Studio 10 Win64" ..

I tried this and it did not work, also I tried cygwin and that also did not work. But I cannot you Visual Studio because of company restriction.. I need Cygwin. Can you help me.

**Comment by davisking** [comment]
What happened in each case when it didn't work?
