### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by skprasadu** [mit-nlp/MITIE#43]
I have seen good number of examples of ner and binary relationship, are there plans for Sentiment Analysis?

Also can I get an example of binary_relation_detector_trainer in Java. It will help.
Thanks in advance.

**Comment by davisking** [comment]
It's something we plan on adding.  There keep being more pressing problems
to solve though so we haven't gotten to it yet :)

The same goes for the java example.

**Comment by davisking** [comment]
Now addressed by PR https://github.com/mit-nlp/MITIE/pull/49
