### ISSUE TITLE
Memory growth in c++ code

### ISSUE THREAD

**Issue by skprasadu** [mit-nlp/MITIE#45]
Hello Davis,

I am training a NER where in I have about 63 sentences with lot of key works per sentence. This is primarily wikipedia extracts and I am training the words for a specific domain. 

My cpp code is @ https://github.com/skprasadu/wikipedia-extraction-framework/blob/master/train_movie_relation/train_my_ner.cpp . And my main code @ https://github.com/skprasadu/wikipedia-extraction-framework/blob/master/train_movie_relation/train_relation_extraction_example.cpp calls the train method.

When I run the training process, it takes a long time, that is understandable, but the memory growth is crazy, it sucks up close to 16gb to complete the NER. Can you see what I am doing wrong?

Can you tell me how to optimize this?

Thanks
Krishna

**Comment by davisking** [comment]
I can't tell from what you posted.  However, the trainer does use a lot of
RAM in general.  Especially if you have a lot of labels.

**Comment by skprasadu** [comment]
What is labels?

**Comment by davisking** [comment]
MITIE finds named entities and labels them.  For example, it finds
"locations" and labels them as such.  The amount of RAM usage is linear in
the number of different label categories.
