### ISSUE TITLE
How to interpret confidence score? 

### ISSUE THREAD

**Issue by Tracy2014** [mit-nlp/MITIE#46]
from the comments in the code base, I understand that the confidence score can range from negative to positive value larger than 1. But it's unclear to me that when I have a result with score 1.3, I'm still not sure how confidence this value is, because I don't have a [min, max] range in mind. If possible, may I have some statistical background in how this value is calculated? thanks!!

**Comment by davisking** [comment]
The outputs are from linear SVMs and have the usual interpretation for such models.

**Comment by dvorka** [comment]
Normally SVM tries to find a decision function for **separating the data** of one class from the data of another one. The prediction is returning the **distance** to this decision function. So the **bigger**, the more sure the data is in the class; and the sign is above or below the decision function, which is the 0 level. -- [sop](https://stackoverflow.com/questions/17136528/svm-confused-at-the-result-and-scores-is-much-greater-than-1-or-1)
