### ISSUE TITLE
Can you explain what features from a word the total_word_feature_extractor extracts?

### ISSUE THREAD

**Issue by imxuyue** [mit-nlp/MITIE#50]
In the example it mentioned it looks at morphological features. What kind of features are they? Thank you!

**Comment by imxuyue** [comment]
I am asking this because I am trying to figure out what languages the library can support.

**Comment by davisking** [comment]
It creates a bunch of indicator features based on the presents of different substrings in each word.  What substrings are used is learned by the word feature extractor.  The substrings are just strings of bytes as far as MITIE is concerned.  So it should work with any language.

**Comment by grafael** [comment]
Let me know if I understood right. It means that I can use the same total_word_feature_vector.dat file for any language? Or I need to create a new one if I decide to train sentences in another language?

**Comment by davisking** [comment]
Well, different languages have different common sub-strings and combination patterns.  So no, you definitely can't reuse a feature extractor on different languages.

**Comment by davisking** [comment]
Even more generally, I wouldn't have made the feature extractor a trainable thing if there was One True Feature Extractor you just used for everything.

**Comment by grafael** [comment]
So, I couldn't find any example (at least in example folder) showing how to train my own feature extractor. There any point in the source code that I could start? I just found an example (python) showing the content of a feature extractor file.

**Comment by davisking** [comment]
You run the wordrep program on a folder of text files and wait.  That's all
there is to it.  There aren't any parameters or anything and one of the
examples tells you what to type even.

**Comment by grafael** [comment]
Thanks @davisking  worked perfectly!
