### ISSUE TITLE
Getting error overlap entity

### ISSUE THREAD

**Issue by maxmert** [mit-nlp/MITIE#52]
Good afternoon.
Thanks for such awesome library.

I'm getting an error `Invalid range given to ner_training_instance.overlaps_any_entity().  It overlaps an entity given to a previous call to add_entity().`.

Can you please explain me what is going on?
Thanks again.

**Comment by davisking** [comment]
No problem.

As the error says, you gave two entities that overlap in the text.  You
can't do that.  I'm not sure how to say it in a clearer way :)

**Comment by maxmert** [comment]
^^^ @davisking Sorry, it was a very stupid question. And a looong baaad day. Thank you for your answer.

**Comment by davisking** [comment]
No worries :)
