### ISSUE TITLE
wordrep raises a std::bad_alloc error when training on new corpus

### ISSUE THREAD

**Issue by raphael0202** [mit-nlp/MITIE#53]
I've tried to used wordrep to train the word embedding on a specialized corpus. However a `std::bad_alloc` occurs during the process:

```
number of raw ASCII files found: 127
num words: 200000
saving word counts to top_word_counts.dat
number of raw ASCII files found: 127
Sample 50000000 random context vectors
Now do CCA (left size: 50000000, right size: 50000000).
std::bad_alloc
```

I've tried to launch gdb (after compiling in DEBUG mode) to see the error, but there is no stacktrace.
The training data is quite large (but fits in RAM), but it contains some non-ASCII characters (the files are encoded in unicode). Could this be due to encoding?

**Comment by davisking** [comment]
No, bad_alloc means you ran out of RAM.  This algorithm requires a lot of RAM, when I trained the existing model I used a machine with 128GB of RAM.

**Comment by raphael0202** [comment]
Thanks for your quick answer.

**Comment by davisking** [comment]
No problem :)

**Comment by raphael0202** [comment]
If you don't mind, I was wondering what was the size of your training set directory? It would help me to determine the amount of memory I need (all my text files are ~700MB)

**Comment by davisking** [comment]
I forget the exact size, but it was the English Gigaword corpus, which is
10s of gigabytes.

**Comment by raphael0202** [comment]
Great, thanks!
