### ISSUE TITLE
Using glove word representation.

### ISSUE THREAD

**Issue by xezr** [mit-nlp/MITIE#54]
Thanks for this great tool. As I read in issues, training new word representation with `wordrep` require lots of memory. Is it possible to use existing word representation in  `glove` format or even convert `glove` output to compatible with MITIE?

**Comment by davisking** [comment]
What is glove?

**Comment by xezr** [comment]
[glove](http://nlp.stanford.edu/projects/glove/) is a vector representation for words.

**Comment by davisking** [comment]
This is not a feature in the MITIE code.  I'm sure it could be done though, but you would need to get into the MITIE code to make the appropriate changes and it's not clear to me you would get any benefit.

**Comment by davisking** [comment]
I should also point out that I can make wordrep use less memory.  But it's not a great idea because you need to run it on a large corpus anyway to get good results.  :)

**Comment by xezr** [comment]
Thanks for your reply, I want to user MITIE on arabic sentences, so I need to train new word model or using existing word models. Would you please share output format of `wordrep` so I could convert `glove` models to `wordrep` compatible models?

**Comment by xezr** [comment]
I forgot to say, I have access to large arabic corpus, so if `wordrep` use less memory I could train word model from scratch.

**Comment by davisking** [comment]
Look at the code to see what wordrep does.  But wordrep also models word morphology and will therefore produce useful outputs for words not in the wordrep training set.  This turns out to be pretty important for generalizing on test data and is something that is usually not present in other word vector models.  

Really the best thing to do is buy more RAM.  RAM is cheap these days :)

**Comment by anujgupta82** [comment]
It may be a good idea to allow other word vector models (Google word2vec, GLOVE etc to plug and play) in MITIE

**Comment by davisking** [comment]
The point of MITIE is to be completely turnkey.  Adding a bunch of options that only experts understand isn't in the spirit of MITIE.  So if you want to middle with how the algorithms works then just use dlib.  In the end, MITIE is really a pretty thin wrapper on top of dlib's machine learning tooling.
