### ISSUE TITLE
Updating mitie in NPM

### ISSUE THREAD

**Issue by ossrapaport** [mit-nlp/MITIE#56]
Are there any plans to update mitie on the NPM? It's almost a year old, and I suspect many users would want to have mitie integration in Node as exists in Java, Python, and other languages.

**Comment by davisking** [comment]
I didn't even know MITIE had node.js packages :)   

I would suggest asking whoever made the node.js binding or NPM package.

**Comment by ossrapaport** [comment]
It certainly does, and having modded it a little I have found it to be a great package! Let me ask if there are any plans for Spanish binary relationship extraction? Much appreciated :)

**Comment by davisking** [comment]
I'm not going to create such models.  But you can train them yourself if you have the data using MITIE's training API.
