### ISSUE TITLE
Str support for python3

### ISSUE THREAD

**Issue by raphael0202** [mit-nlp/MITIE#66]
MITIE currently needs every str to be encoded in bytes in Python3. As I'm mainly using Python3, I've modified mitie.py to deal with unencoded strings (unicode in Python2 or str in python3), and to encode them before calling ctypes functions. I also returned str instead of bytes in Python3 for every function that was returning strings, as this is the default string type in Python3.
Would you be interested in a pull request?

**Comment by davisking** [comment]
Sure, sounds like a good improvement :)

**Comment by raphael0202** [comment]
I've submitted a pull request, the code should be fully python3 compatible :)
