### ISSUE TITLE
Multi-core in text categorizer training

### ISSUE THREAD

**Issue by avitale** [mit-nlp/MITIE#68]
Hi Davis,

Is there a way to use multiple cores in the text categorizer training?
I have tried setting the number of threads, both in C++ and in python. I can see the number of threads changing accordingly but all the threads use the same core. 
I made the tests under OS X El Capitan.

Thank you very much!

**Comment by davisking** [comment]
How big is your training set?   Also, linking to a BLAS library will help with speed a bit as well.

**Comment by avitale** [comment]
~150 samples, 12 classes. Training time > 2 hours

**Comment by davisking** [comment]
That's too few samples to get any significant parallelism.  However, 2
hours is extremely long for such a small dataset.  I've used that thing on
datasets with hundreds of thousands of samples.  Are you sure compiler
optimizations are on?

**Comment by avitale** [comment]
No, I'm not sure compiler optimizations are on, I've just compiled with make under mitielib. Should I do something different?
I can also try using cmake and linking a BLAS library.

**Comment by davisking** [comment]
Then optimizations are on.

Maybe your data is impossible to classify and the optimizer is spending a
huge number of iterations trying to figure out how to do it.  That can
cause issues sometimes.

**Comment by avitale** [comment]
I thought so at the beginning, but it actually performs pretty well on both training and holdout datasets.
I'll try with a BLAS library and providing more samples and see if things change.
Thank you very much Davis!

**Comment by avitale** [comment]
Linking to BLAS brought multicore, still very long time to train.
As a solution, I split the classifier in multiple cascading ones, each with less classes.
To deploy multiple classifiers, it would make sense to do the sentence embedding outside of text_categorizer::predict and avoid saving the total_word_feature_extractor together with each text_categorizer.
If I find time to do it I'll submit a PR.
