### ISSUE TITLE
Can't set num_threads from Python for NER training

### ISSUE THREAD

**Issue by ahalterman** [mit-nlp/MITIE#7]
I'm training a new NER model in MITIE on a machine with a bunch of cores. Training it with a few thousand samples takes a couple hours, so I'd really like to be able to multithread it. When I set it in my code, though, it seems to default to 4 regardless of what I set.

```
import sys, os, json
sys.path.append("/home/ahalterman/MITIE/mitielib")
from mitie import *
from collections import defaultdict

trainer = ner_trainer("/home/ahalterman/MITIE/tools/wordrep/build/total_word_feature_extractor.dat")
trainer.num_threads = 8

[all the other stuff here]
```

When I start the training, though, it says only 4 threads are in use:

```
now do training
C:           20
epsilon:     0.01
num threads: 4
cache size:  5
loss per missed segment:  3
```

Sure enough, running `ps -o nlwp <pid>` says it's got 5 threads (I don't know much about multithreading so I'm not sure what that extra one is).

Any idea what's going on?

**Comment by Tejaf** [comment]
what does num_thread means please? does it refer to the number of sample data you pass in. I'm a little confused.
