### ISSUE TITLE
Removing noise from training sets

### ISSUE THREAD

**Issue by jluisreymejias** [mit-nlp/MITIE#71]
Hello,

I'm trying to remove noise from training sets for text classification, all my documents looks like invoices, purchase orders, letters....

Company X
Address

CustomerId          Invoice Number    Purchase date
121323                 INV1111                01/01/2016

Item code  amount
1       XXXX    54.4
2       YYYY     24.4
3       ZZZZ      11.4

Total xxxx
Tax xxx

Signature                                     company foot....

So, I'm interested on a general guideline of what should be removed or codified on the training set (example, change codes by #code# tag, amounts for an #amount#, items that will increase training time without sense...)

Also I'm thinking in preprocessing the documents with an entity recognizer and replace main keys like Invoice Number or company name (usually represented as InvNo: Document Number, Invoice number, InvoiceNo...) whitch neutral tags like #invno#, will this increase recognition accuracy on the text classificator ?

Kind regards
J.

**Comment by davisking** [comment]
Any sort of cleanup you can do is usually helpful.  Removing invoice numbers and replacing them with some tag is a good example of that.  More generally, anything you can automate without machine learning is something you should automate.  Machine learning is only what you use when you have run out of normal coding techniques to solve part of a problem.
