### ISSUE TITLE
Dude at character level learning

### ISSUE THREAD

**Issue by jluisreymejias** [mit-nlp/MITIE#74]
Hello, 

Another question, it's MITIE able to classiffy entities based just on the character structure, without context, ex:

VAT NUMBERS:
ESB12345678
IRC12345324
GBB12345678
.....

FLIGHT CODES:
BT0455
AT1455
AA1455
.....

So if I pass 10K samples of each category without any other context text, will the classifier identify the entities correctly or not ?

Kindest regards
J.

**Comment by davisking** [comment]
The only way to know is to try it and see :)
