### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by edevil** [mit-nlp/MITIE#77]
Python 3 is the current stable version, it would be nice to support it.

**Comment by davisking** [comment]
Is that a question?  People use python 3 with MITIE.

**Comment by edevil** [comment]
Well, the documentation mentions support for Python 2.7 explicitly, and I ran one of the examples using Python 3 and got a typical error of non Python2->3 conversion:

```
Traceback (most recent call last):
  File "categorize_text.py", line 23, in <module>
    cat = text_categorizer("new_text_categorizer.dat")
  File "//anaconda/envs/mitie/lib/python3.5/site-packages/mitie/mitie.py", line 660, in __init__
    raise Exception("Unable to load text_categorizer detector from " + filename)
TypeError: Can't convert 'bytes' object to str implicitly
```
(The underlying problem was that I did not have the dataset in place, but it gave an indication that the code was not Python 3 ready).
