### ISSUE TITLE
Documentation for Java on OS X

### ISSUE THREAD

**Issue by charlieg** [mit-nlp/MITIE#8]
I ran into a few problems on OS X with the instructions for [Using MITIE from a Java program](https://github.com/mit-nlp/MITIE/blob/master/README.md#using-mitie-from-a-java-program):

> Also note that you must have Swig 1.3.40 or newer, CMake 2.8.4 or newer, and the Java JDK installed to compile the MITIE interface.

In addition, it was necessary to install [FFTW](http://fftw.org/) to get the build scripts to work properly. Without it, I was getting errors like `error: fftw3.h: No such file or directory`.

> That will place a javamitie shared library and jar file into the mitielib folder.

The build scripts created the `javamitie.jar` and `libjavamitie.jnilib` files, but I had to move them from `MITIE/mitielib/java/build/lib` into `MITIE/mitielib` manually. Otherwise, I saw errors like this when trying to compile NerExample.java: `NerExample.java:6: error: package edu.mit.ll.mitie does not exist`.

> Once you have those two files you can run the example program in examples/java by running run_ner.bat if you are on Windows or run_ner.sh if you are on a POSIX system like Linux or OS X.

In `run_ner.sh`, `export LD_LIBRARY_PATH=../../mitielib` doesn't have the desired effect in OS X -- you'll wind up with errors like this:
```
Native code library failed to load. 
java.lang.UnsatisfiedLinkError: no javamitie in java.library.path
```
You need to use `DYLD_LIBRARY_PATH=../../mitielib` instead, or set it using the `-Djava.library.path` VM option.

**Comment by arjunmajum** [comment]
@charlieg, thanks for pointing out the bug. It should be fixed now.

**Comment by charlieg** [comment]
Sweet, thanks!
