### ISSUE TITLE
NER cannot find entities

### ISSUE THREAD

**Issue by evotianusx** [mit-nlp/MITIE#86]
Hi there,

Let me get straight to the point, here is the list of what I've done

I've created my own Total word feature extractor using the provided tools.
Loaded said model into the NER trainer, add samples, and then run the training.
I've used around 500 paragraph worth of formal news media. The training takes a bit of time but in the end it finished without error.

I then test the model using few entities in the training samples, it failed to recognize any of them

Then I tried training again, with the same TWFE and configuration but this time only 1-2 sentences as example. This way, the model can recognize the said entities. 

Any idea why this happened? Should I just get more data to feed into the system in hope it will get more confident  with its prediction? 

Is it required that each training instance must have at least one tag entity in them? or is it the case that each training examples must contain all the entities that we are looking for?

Thank you

**Comment by davisking** [comment]
If it doesn't work even on the training data then you have probably done something wrong.  Maybe you aren't loading your data correctly, are putting the tags in the wrong places, or something like that.

**Comment by evotianusx** [comment]
![mitie](https://cloud.githubusercontent.com/assets/7891922/21756538/085bfb5a-d655-11e6-9520-bcee27bb6182.png)

thanks for the quick reply. I dont think that the wrong tagging is what caused it. Please take a look at the attached image. My program will split the " _ " and assign it as the tag. As you can see sometimes it can find a hit sometimes it misses it.  
Even in the same sentence, some of the tagged words is recognized while some is missed.

The function NER is just a helper function to call the tokenizing and the tagging of the model

**Comment by evotianusx** [comment]
Do I need each tag instances on each of the training instances? Like on your examples, the 2 samples both have person and location tagging to them.

**Comment by davisking** [comment]
No, you don't need to have all possible tags on each instance.  

In any case, if it doesn't work on your training data something is almost certainly wrong with your code.  Consider the example programs, they have tiny training datasets but work fine.  Make sure you are really feeding the data back in the same way during testing.  Maybe you are tokenizing it differently when you go to test.  Beats me.

**Comment by evotianusx** [comment]
In both of the case I use the tokenize() function from the mitie, the same one you used on the python examples.

**Comment by stefan-it** [comment]
Can you provide the training script and the sample file here, so we can look into it a more deeper?

**Comment by evotianusx** [comment]
I think I figured out what went wrong, some of my training samples does not have any NER instance however my script add them to the training set regardless, I have put in an IF check condition, and re-training it again

**Comment by SakthivelAnand** [comment]
Hello,
I am trying to execute the NER example program that you are given on github....
i can't compile ,,it shows the error like

Native code library failed to load. 
java.lang.UnsatisfiedLinkError: no javamitie in java.library.path

i referd it on discussion...I got a one idea to run it by using .sh file....as

export LD_LIBRARY_PATH=opt/etc/MITIE/mitielib
export CLASSPATH=opt/etc/mitie-0.1.jar:.
javac NerMitie.java
java NerMitie

but...This method also does not work...
Please help me...
Thank you ....in advance

**Comment by davisking** [comment]
Did you follow the exact instructions on the mitie front page? https://github.com/mit-nlp/MITIE  It tells you what to type.

**Comment by SakthivelAnand** [comment]
Yaa...I did...Where the shared library stored in the mitielib directory(Name of the library)..i can't find it
May be this caused those problem.
Thank you

**Comment by davisking** [comment]
The java examples come with scripts like run_ner.sh.  Run that script, or look at it's contents.  It contains the java command that correctly adds MITIE to the classpath and library load path.
