### ISSUE TITLE
MITIE install fails on Windows 10

### ISSUE THREAD

**Issue by maxiz** [mit-nlp/MITIE#87]
Hi,

I'm trying to install MITIE backend on windows 10 using pip install git+https://github.com/mit-nlp/MITIE.git. However the install fails at the build step with the following error message.
`Collecting git+https://github.com/mit-nlp/MITIE.git
Cloning https://github.com/mit-nlp/MITIE.git to c:\users\njones\appdata\local\temp\pip-97mlgx-build
Installing collected packages: mitie
Running setup.py install for mitie: started
Running setup.py install for mitie: finished with status 'error'
Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;file='c:\users\njones\appdata\local\temp\pip-97mlgx-build\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\njones\appdata\local\temp\pip-ydwrn7-record\install-record.txt --single-version-externally-managed --compile:
running install
running build
error: [Error 2] The system cannot find the file specified

----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;file='c:\users\njones\appdata\local\temp\pip-97mlgx-build\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\njones\appdata\local\temp\pip-ydwrn7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\njones\appdata\local\temp\pip-97mlgx-build`

Any suggestions on I could be doing wrong would be really helpful!

Thanks

**Comment by davisking** [comment]
That doesn't look like the entire output from the build process. So it's impossible to say anything.

**Comment by evotianusx** [comment]
Have you tried installing it again this time use an administrator
credentials. It said that the file cannot be found ( or pip is not allowed
to access the files)

**Comment by abubakarsohail** [comment]
I am having the exact same error while installing MITIE on Windows 10. Please check the screenshot attached.
$ pip install git+https://github.com/mit-nlp/MITIE.git
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\abubak~1\appdata\loca                                                                                                                l\temp\pip-iosonl-build
Installing collected packages: mitie
  Running setup.py install for mitie: started
    Running setup.py install for mitie: finished with status 'error'
    Complete output from command c:\python27\python.exe -u -c "import setuptools                                                                                                                , tokenize;__file__='c:\\users\\abubak~1\\appdata\\local\\temp\\pip-iosonl-build                                                                                                                \\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\                                                                                                                r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:                                                                                                                \users\abubak~1\appdata\local\temp\pip-zyrmfi-record\install-record.txt --single                                                                                                                -version-externally-managed --compile:
    running install
    running build
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\                                                                                                                \users\\abubak~1\\appdata\\local\\temp\\pip-iosonl-build\\setup.py';f=getattr(to                                                                                                                kenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();ex                                                                                                                ec(compile(code, __file__, 'exec'))" install --record c:\users\abubak~1\appdata\                                                                                                                local\temp\pip-zyrmfi-record\install-record.txt --single-version-externally-mana                                                                                                                ged --compile" failed with error code 1 in c:\users\abubak~1\appdata\local\temp\                                                                                                                pip-iosonl-build\
![capture](https://cloud.githubusercontent.com/assets/20099503/21924705/12696fc0-d99c-11e6-9caf-327644fbd95a.PNG)

**Comment by davisking** [comment]
Just run cmake on it's own rather than `python setup.py`.  What does cmake say?

**Comment by davisking** [comment]
The cmake build instructions are shown here: https://github.com/mit-nlp/MITIE

**Comment by abubakarsohail** [comment]
The thing is I am working on rasa.ai. I was following their tutorial. There was this link "pip install git+https://github.com/mit-nlp/MITIE.git". By the way I have successfully build using cmake. But don't know what to do next. I need it working with rasa.ai which is written in Python. Can you help?

**Comment by davisking** [comment]
The front page of MITIE shows how to use it with python.  Once you have it built you can run the python examples.

**Comment by abubakarsohail** [comment]
As I told you, the build was successful. But I don't know what to do next. When I try to run from one of the python examples, the system is unable to find the specified module. 
![capture](https://cloud.githubusercontent.com/assets/20099503/21931474/6d6999ec-d9bd-11e6-8c77-0d1ed71972e2.PNG)

**Comment by abubakarsohail** [comment]
My friend was able to install mitie successfully on linux using this command "pip install git+https://github.com/mit-nlp/MITIE.git". Why can't I do the same on Windows?

**Comment by davisking** [comment]
I have no idea.  But if you follow the instructions on the front page exactly you can definitely get the MITIE examples working.

**Comment by maxiz** [comment]
@davisking That's the complete output I got on the console when I ran `pip install git+https://github.com/mit-nlp/MITIE.git`. 

@evotianusx  I even tried to run this as an administrator but got the same error.

I'll try running cmake and see if it builds successfully.

**Comment by abubakarsohail** [comment]
@maxiz Were you able to build and use MITIE successfully? If so, can you please guide me as well? I have build MITIE using cmake but I am stuck on the next part. Don't know how to use it.

**Comment by davisking** [comment]
@abubakarsohail You ran the cmake commands exactly as shown on the MITIE front page, then you ran one of the python examples.  What happened?

**Comment by abubakarsohail** [comment]
@davisking I was just supposed to run the scripts using python, right? Please check the screenshot.
![capture](https://cloud.githubusercontent.com/assets/20099503/21984979/7548c304-dc1a-11e6-87c2-d361e5c5baff.PNG)

**Comment by davisking** [comment]
Did you run these commands first?

```
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```

**Comment by abubakarsohail** [comment]
Yes, I did. The build was successful. Is there any way to confirm the build was successful or not? The output showed 0 errors and some 180 warnings. If you want, I can run these commands again with a fresh repo clone.

**Comment by davisking** [comment]
Those commands output the mitie library that python opens.  They either work or they don't.  That error you are posing is a file not found for the mitie library file.  Look and see if it exists.   You either have the file or you don't.  This should be simple to debug.

**Comment by abubakarsohail** [comment]
Did everything from the start. Seems everything is working fine now. Thanks @davisking

**Comment by HardikShah289** [comment]
Hi @abubakarsohail ,
I am facing the same issue. Using Cmake I have build. but when running any python py script it giving me same error as you got "Module not found". (Jan 16 snapshot).
What did you do next?
Thanks in advanced? I am using x64 bit laptop. do i need to install python x64 bit too? I am also trying to connect it with rasa.ai.

thanks for you all help.

**Comment by davisking** [comment]
If it built then there is a mitie.pyd file, just put it in your python path.

**Comment by HardikShah289** [comment]
There is mitie.pyc but not mitie.pyd file.

**Comment by davisking** [comment]
Did you type these commands?

```
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```

**Comment by HardikShah289** [comment]
when you said python path, do i need put it inside Python installed path or path from where my ner.py is?
Thanks sir for your help.

**Comment by HardikShah289** [comment]
I ran your given commands. Output: 157 warning 0 errors.

Still no mitie.pyd file, but it has created mitie.dll, mitite.lib file.

**Comment by davisking** [comment]
Do the examples in the examples folder run?

**Comment by andikas** [comment]
Hi all, 
@abubakarsohail @davisking 

I got the same problem with abubakarsohaiil.
i want to use MITIE too at my Rasa NLU.
please help me how to install that mitie. i got the same error. i dont know how to use cmake. cmake not recognized by command prompt.

thanks before for all you guys.
cheers,

**Comment by abubakarsohail** [comment]
You need to install cmake first.

**Comment by andikas** [comment]
Hi @abubakarsohail ,

Thanks for your quick respond.
Look like I can't access their official website for now. the site always can't be reached.
I'll give some feedback if I've installed cmake.

Thanks,
Cheers,

**Comment by andikas** [comment]
Hi @abubakarsohail,

I've installed cmake, and I download all files from https://github.com/mit-nlp/MITIE.
how do I install the mitie with cmake?
![image](https://cloud.githubusercontent.com/assets/25953422/26613154/8f5dd012-45e3-11e7-965a-8df9b182d005.png)
please guide me..

Thanks,
cheers

**Comment by davisking** [comment]
The front page, https://github.com/mit-nlp/MITIE, tells you what to type.

**Comment by andikas** [comment]
Hi @davisking,

I know and i've followed that code.
i just confuse why when I run 'python -m rasa_nlu.train -c config_mitie.json', I still asked to install mitie.
I've download mitie from this github and run that code (the screenshot from my previous comment).

I want to ask abubakar how he continue it to rasa.ai?
are there something wrong with my folder structure so I keep asked to instal mitie?

Thanks,
Cheers

**Comment by abubakarsohail** [comment]
Okay. Here's how I got it working. I made a folder named 'mitie' in the Lib folder of python installation and copied 3 files names '__init__.py', 'mitie.py' and 'mitie.dll' in it. Try running rasa again and let me know if it helps.

**Comment by davisking** [comment]
Well, I don't know anything about rasa or any of the people who work on it.  So this isn't the right place to ask about rasa.

**Comment by andikas** [comment]
Hi @davisking,
Thanks for the reminder.

Hi @abubakarsohail,
I have create a new issue in rasa_nlu, hopefully you could help me there.
https://github.com/RasaHQ/rasa_nlu/issues/410

Thanks all,
Cheers

**Comment by devepro** [comment]
@abubakarsohail Thanks a lot..!! your solution worked

**Comment by modadugu** [comment]
@abubakarsohail can you share the pyhton binaries generated for mitie package.. current package on mitie is out of sync with the master.

**Comment by abubakarsohail** [comment]
Hey there. I don't have them right now since I stopped working on it. I am sorry.

**Comment by teja463** [comment]
@modadugu Attached the generatef files. I am using python 64 bit. See if those are usefull


[mitie.zip](https://github.com/mit-nlp/MITIE/files/1547669/mitie.zip)

**Comment by cjhurst** [comment]
I had this issue. pip install cmake.... fixed.

**Comment by kyang888** [comment]
> I had this issue. pip install cmake.... fixed.

thanks, it work for me.
