### ISSUE TITLE
Why choose Eigenwords: Spectral Word Embeddings as word embedding model?

### ISSUE THREAD

**Issue by kwkwvenusgod** [mit-nlp/MITIE#89]
As far as we know that word embedding as a basis of NLP which can be applied in NER  etc, many researchers make efforts in this field.  The most popular models which are used are Word2vec and gloVe. The method you are using is one paper  in 2015 with the citation of 15. How do you make the decision on using this not the most popular ones? Is there any specific purpose in the consideration of different characteristics of the algorithms?

**Comment by korokokou** [comment]
I'm might be off subject but could someone explain to me what are Spectral word embedding or redirect me to ressources about this subject...??

**Comment by davisking** [comment]
@kwkwvenusgod What's popular is not always the best.  When I compared spectral word embeddings to word2vec during MITIE development I found that word2vec wasn't better.  Moreover, the spectral word embeddings can be quickly and reliably estimated without any user fiddling.  The spectral technique also lends itself to an out of sample projection in a way that the deep learning methods didn't.  For example, if you give MITIE a word it hasn't seen before it is still able to produce a spectral word vector for it by mapping the set of all substrings of the word into the spectral word vector space.  

In any event, if you want to try the comparison yourself it's plenty easy to replace the spectral word vectors with any other word vectors and run MITIE and see what happens.  

@korokokou This is a good first paper to read about it: http://icml.cc/2012/papers/763.pdf

**Comment by korokokou** [comment]
thanks for the info ^^

**Comment by kwkwvenusgod** [comment]
I can see your point. But I am curious whether you have tried GloVe previously. If you have done this, how about the performance? Thank you very much

**Comment by davisking** [comment]
I haven't tried GloVe.
