### ISSUE TITLE
Questions about generating  total_feature_word_extractor with wordrep

### ISSUE THREAD

**Issue by korokokou** [mit-nlp/MITIE#90]
I was training wordrep with a corpus of around 2giga and my computer died on me.
Since the time took for this, i'm wondering, is there any way to train little by the little the algo, or do i have to use an enormous corpus and pray gods my computer hold on...??
Furthemore, since i'm working on a french corpus, any special requirement i have to be worried about or can i keep doing what i does. 
Thanks for reading, and cudos to the developpers that's a wonderfull work you did here.

**Comment by davisking** [comment]
No problem :)

Make sure you install a good BLAS library like the Intel MKL.  That will make wordrep run much faster.  I trained the model that comes with MITIE on the gigaword dataset and it took a few hours or so using the Intel MKL.

No, it's not incremental.

**Comment by korokokou** [comment]
Thanks for the answer. I have an other question, How many ram should i get if i want to drastically improve  my learning time.?? i'm currently at 8Gb.

**Comment by davisking** [comment]
If you aren't getting errors about running out of RAM then you have enough.

**Comment by korokokou** [comment]
Hi again.
I finally chose 16 and, with some swap, managed to survives. Does Openblas have any impact on wordrep.?? I'm watching htop and it does'nt seem there is any multicore usage going on. Maybe i'm missing something....... Furthmore, i'm eager to avance the project. How could i help...??

**Comment by davisking** [comment]
Yes, using a multi-core BLAS library like openblas will make a big
difference in speed.

**Comment by korokokou** [comment]
That's what i thought.  Is there any option i have to activate to make sur wordrep use openBLAS..?? I'm currently doing somme computing on a AWS machine and it seems that there is only one core currently in use. I'm made sure mitie detect the library at compilation, so i don't understand where is my fuck up.

**Comment by davisking** [comment]
No, CMake should find it automatically.  The MITIE compilation will print a message to the effect of "Hey, I found BLAS and I'm using it."   If it's using BLAS then it's using BLAS and the BLAS library does whatever it does.  However, maybe you have a copy of openblas that doesn't use multiple cores.  I don't know.

**Comment by cmllmrnn** [comment]
Hello! Whenever I'm running corpora with more than 21,000 words, it stops after counting the number of raw ASCII files and it says "bad allocation". I can run those that have 20,000 number of words. I have 7GB RAM.
