### ISSUE TITLE
Using MITIE with french language

### ISSUE THREAD

**Issue by tarikd** [mit-nlp/MITIE#91]
Hi everyone,

I want to use MITIE on french but I'm unable to find documentation on how to do this or if it is already available out-of-the-box.

If not, could you please tell what are the steps that I have to go through to get MITIE to work on french? Is there some training to do? If yes, on which corpus...

Are Wikiner (http://schwa.org/projects/resources/wiki/Wikiner) or the French Universal Dependencies treebank (https://github.com/UniversalDependencies/UD_French) relevant for this?

Thank you for your help!

**Comment by davisking** [comment]
There are no French models included with MITIE.  So if you want to do some NER with French then it's up to you to train whatever sort of tagging model is appropriate for your problems.  The examples folder contains example programs showing how to train MITIE.  However, what data you need for that depends entirely on what you want to do.
