### ISSUE TITLE
Progress indicator for wordrep tool

### ISSUE THREAD

**Issue by rhazegh** [mit-nlp/MITIE#93]
I have been running it on 13GB of plain text corpus on an amazon EC2 instance (r4.4xlarge, 122GB RAM, 16 CPUs). Maximum memory utilization I observed was 70% and only 1 CPU is being used.

```
$ wordrep -e ./enwiki-corpus-20170201_text/
number of raw ASCII files found: 1
num words: 200000
saving word counts to top_word_counts.dat
number of raw ASCII files found: 1
Sample 50000000 random context vectors
Now do CCA (left size: 50000000, right size: 50000000).
```

It is still running after 26 hours and I am not sure how much longer it will take to finish.

```
top - 16:42:49 up 1 day,  2:38,  3 users,  load average: 1.00, 1.00, 1.00
Tasks: 230 total,   2 running, 228 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.3 us,  0.0 sy,  0.0 ni, 93.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 12582760+total, 19989104 free, 90735088 used, 15103408 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 34253856 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                
 14650 develop+  20   0 86.085g 0.084t   3788 R 100.0 71.7   1583:49 wordrep  
```

I was wondering if it is possible to have some kind of progress indicator for the wordrep tool?

**Comment by davisking** [comment]
You could go into the code and print some progress statements if you want.  But yes, it will take a long time.   Although, it doesn't sound like you compiled it against a BLAS library, which you should definitely do if you want it to run fast.  I would recommend using the Intel MKL since it's the best.  OpenBLAS is also reasonable as well, but not quite as good.

**Comment by rhazegh** [comment]
Thanks for the recommendations. I complied against OpenBLAS. I will try Intel MKL to see if it makes a difference.

**Comment by davisking** [comment]
OpenBLAS is normally multithreaded.  Maybe the version you have isn't
configured that way.  But if you download a copy from the openblas web site
you can compile it easily and it will be multithreaded by default.

**Comment by cbonadio** [comment]
Hello

I compiled against Intel MKL, but it still uses only on CPU on an Amazon R3.4xlarge 122GB instance 

Running:
./wordrep -e /home/txt

number of raw ASCII files found: 730
num words: 200000
saving word counts to top_word_counts.dat
number of raw ASCII files found: 730
Sample 50000000 random context vectors
Now do CCA (left size: 41563228, right size: 41563228).

On compiling I got:

-- Searching for BLAS and LAPACK
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found Intel MKL BLAS/LAPACK library
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring done

Is there anything else that need to be set to use all CPUs 

%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu8  :  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu9  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu10 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu11 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu12 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu13 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu14 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu15 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st

Thanks

**Comment by rhazegh** [comment]
I deletes my original OpenBLAS, downloaded the source code and compiled it. Got this:

```
OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (command line : gcc)
  Fortran compiler ... GFORTRAN  (command line : gfortran)
  Library Name     ... libopenblas_haswellp-r0.2.20.dev.a (Multi threaded; Max num-threads is 16)
```

Complied wordrep against this new OpenBLAS and it still uses only one CPU when doing the CCA.

**Comment by davisking** [comment]
Is MITIE compiled to use it?  What did you do to compile MITIE?

**Comment by cbonadio** [comment]
I downloaded the openblas from their github compiled and installed on /usr/local/openblas

on MITIE

cd tools/wordrep
mkdir build
cd build 
cmake -DCMAKE_LIBRARY_PATH=/usr/local/openblas/lib ..
cmake --build . --config Release --target install

./wordrep -e /home/ubuntu/MITIE/todos-utf/ &
[1] 32492
root@ip-172-30-0-207:/home/ubuntu/MITIE/tools/wordrep/build# number of raw ASCII files found: 730
num words: 200000
saving word counts to top_word_counts.dat
number of raw ASCII files found: 730
Sample 50000000 random context vectors
Now do CCA (left size: 41563228, right size: 41563228).

But still uses only one CPU.

I found this link, it says there is some problem with lapack, but it is old.
https://github.com/xianyi/OpenBLAS/issues/244

**Comment by rhazegh** [comment]
> Is MITIE compiled to use it?  What did you do to compile MITIE?

Yes. When `cmake ..` is executed it shows that is has detected the OpenBLAS. Only after this I make the wordrep binary.

**Comment by davisking** [comment]
Actually, the CCA step isn't going to make heavy use of the multi-core
aspects of BLAS since most of the computation happens inside the sparse
vector code in dlib which isn't multi-threaded.  It's been a long time
since I ran wordrep so I forgot about this.   But in any case, it does take
a long time to run.  But you only run it once so it's not a big deal.  Just
be patient and it will finish.

**Comment by cbonadio** [comment]
Just to report the status, it finished after 36 hours on a r4.4xlarge instance using the  Intel MKL BLAS. As you pointed it really used only used 1 CPU.

Thanks very much.

**Comment by shgidi** [comment]
Hi @rhazegh , did you find any solution re the progress montioring?
