### ISSUE TITLE
error in persisting the trained model to disk

### ISSUE THREAD

**Issue by sjjpo2002** [mit-nlp/MITIE#95]
I get this error that is not very descriptive:

```
 File "C:\MITIE-master\mitielib\mitie.py", line 706, in save_to_disk
    if (_f.mitie_save_text_categorizer_pure_model(filename, self.__obj) != 0):
WindowsError: exception: access violation reading 0x00000084 
```

**Comment by davisking** [comment]
Post a minimal python program that runs and reproduces this error.

**Comment by abubakarsohail** [comment]
I am having the exact same issue. Please check the screenshots.
![1](https://cloud.githubusercontent.com/assets/20099503/23315088/8c7bbcbc-fae6-11e6-87fa-f5833bd84f0f.PNG)
![2](https://cloud.githubusercontent.com/assets/20099503/23315092/8efdb742-fae6-11e6-8208-83259547105f.PNG)
![3](https://cloud.githubusercontent.com/assets/20099503/23315093/91daf31c-fae6-11e6-8db6-e01b568d076d.PNG)

**Comment by davisking** [comment]
**_Post a minimal python program that runs and reproduces this error._**

**Comment by abubakarsohail** [comment]
I am using rasa_nlu. I am still a beginner. I am using rasa_nlu to train the model.

**Comment by davisking** [comment]
I have no idea what rasa_nlu is.  As far as I know the bug is probably in this rasa_nlu thing and not at all related to mitie.

**Comment by abubakarsohail** [comment]
Okay. Thanks.
