### ISSUE TITLE
Unable to install MITIE on windows 10 machine

### ISSUE THREAD

**Issue by abcdesai** [mit-nlp/MITIE#98]
I get the following error when I try to install.

Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\shyam\appdata\local\temp\pip-ywjmxk-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
    Complete output from command C:\Users\Shyam\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\shyam\\appdata\\local\\temp\\pip-ywjmxk-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\shyam\appdata\local\temp\pip-e9bh0z-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Users\Shyam\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\shyam\\appdata\\local\\temp\\pip-ywjmxk-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\shyam\appdata\local\temp\pip-e9bh0z-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\shyam\appdata\local\temp\pip-ywjmxk-build\

**Comment by davisking** [comment]
Follow the instructions on this page: https://github.com/mit-nlp/MITIE

**Comment by expatiating** [comment]
@davisking, I am not following your comment and I recommend this issue be reopened. I too have been unable to install and use on Windows 10, is there a specific section of the README to follow? I tried following the directions under [Using MITIE from a Python 2.7 Program](https://github.com/mit-nlp/MITIE#using-mitie-from-a-python-27-program)

I get the same error as above when I run `pip install git+https://github.com/mit-nlp/MITIE.git` and when I run `pip install git+https://github.com/mit-nlp/MITIE.git#egg=mitie` (this is the recommended resolution in the Error message when the model fails to load) 

I am attempting to use MITIE from Python on Windows 10. After the above error occurred, I cloned this repo and attempted to install via pip locally as follows:
```
> git clone https://github.com/mit-nlp/MITIE.git
> pip install -e path\to\mitie
```
Then it appears installed correctly when I use the following:
```
> pip list
> mitie (0.2.0, c:\path\to\mitie)
```
But then I still cannot get it run from another python program, I am attempting to use with [Rasa NLU](https://github.com/RasaHQ/rasa_nlu)

I have it working on a Mac following similar steps, however I have a requirement to support Win10. 
If you have any thoughts or recommendations - those are definitely welcome.

I'm no expert at python so there may be something simple I missing :)

**Comment by davisking** [comment]
Use the CMake based instructions and it will work.

**Comment by liujie19880815** [comment]
成功解决了我的问题，感谢

**Comment by chensaics** [comment]
I use this method and successfully resolved this probelm.
> git clone https://github.com/mit-nlp/MITIE.git
> pip install -e path\to\mitie
