### ISSUE TITLE
Did not generate dll files for windows

### ISSUE THREAD

**Issue by mvsrao** [mit-nlp/MITIE#99]
I downloaded the project on Windows 10 machine and executed the install with g++ compiler using python setup.py install command.  It generated libmitie.so file (non-windows environment) and however it did not generate corresponding dll files for Windows environment. Please let me know If I am doing anything wrong

Regards
Rao

**Comment by davisking** [comment]
Try using the cmake install instructions.

**Comment by mvsrao** [comment]
Thank you for your help. I tried to run cmake with Visual studio C++ build tools with following commands 

cmake -G "Visual Studio 15" -T v140 ..
cmake --build . --config Release --target install

The first one ran with 2 build failures and second one ran with 185 warnings and 0 errors. Please find the log file for errors from 1st command.  It generated the single dll: mitie.dll . But when I try to run example programs with that DLL, it gave an error : WindowsError: [Error 193] %1 is not a valid Win32 application


I have noticed the Precompiled shared libraries for python under https://github.com/mit-nlp/MITIE/releases/download/v0.4/mitie-v0.2-python-2.7-windows-or-linux64.zip

But it seems to be bit old compared to the source. Could it be possible to upload the latest precompiled shared library for Python 


[CMakeError.txt](https://github.com/mit-nlp/MITIE/files/812734/CMakeError.txt)

Thanks again for your help

Regards
Rao

**Comment by davisking** [comment]
Delete everything.  Then type these exact commands:
```
cd mitielib
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
```
What is the output?

**Comment by mvsrao** [comment]
I have got following error@ cmake ..
-- Building for: Visual Studio 10 2010
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  No CMAKE_C_COMPILER could be found.

CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/DEVELOPMENT/SOFTWARES/MITIE-master/mitielib/build/CMakeFiles/CMakeOutput.log".
See also "C:/DEVELOPMENT/SOFTWARES/MITIE-master/mitielib/build/CMakeFiles/CMakeError.log".


Note: I don't have Visual Studio 10 2010 and I couldn't find it on the microsoft so I installed Microsoft VC++ 2015 build tools and tried to execute earlier with cmake passing the MS Studio version 2015 

Thanks
Rao

**Comment by davisking** [comment]
You don't need visual studio 2010, 2015 is fine.  But something is obviously wrong with your computer if CMake can't find visual studio 2015.  It's not installed correctly.  So this doesn't have anything to do with MITIE.  

To clarify, you don't need to tell cmake the name of visual studio.  It will find it if it's installed correctly, but that doesn't seem to be the case.
